#!/bin/bash

DB_NAME="skytrondb_main"
DB_USER="dbadmin"
DB_PASSWORD="lask1028zmnx"

sudo -u postgres psql <<EOF

CREATE DATABASE $DB_NAME;
CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';

\c $DB_NAME

GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;
GRANT ALL ON SCHEMA public TO $DB_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $DB_USER;
GRANT USAGE, CREATE ON SCHEMA public TO $DB_USER;

EOF