# Start from an official Python image - using bullseye instead of buster
FROM python:3.9-slim-bullseye

# Install required system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    wkhtmltopdf libmagic1 \          
    libssl-dev \          
    libffi-dev \    
    build-essential \     
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install --upgrade pip
RUN pip install \
    geopy \
    django \
    djangorestframework \
    markdown \
    django-filter \
    django-bootstrap4 \
    django-bootstrap-datepicker-plus \
    drf_spectacular \
    django-cors-headers \
    django-extensions \
    psycopg2-binary \
    pandas \
    django-environ \
    scipy \
    pillow \
    pycrypto \
    django-csp \ 
    python-docx \
    pdfkit \
    whitenoise \
    paho-mqtt  \
    gunicorn \
    django \
    djangorestframework \
    requests \
    numpy \
    pandas \
    scipy \
    pycryptodome \
    python-docx \
    pdfkit \
    docx2pdf \ 
    django-filter \
    django-cors-headers bleach python-magic\ 
    gunicorn \
    django-redis

# Set the working directory in the container
WORKDIR /app

# Create keys directory first
RUN mkdir -p /app/keys

# Copy certificate files - they are required for the MQTT client
COPY keys/ca.crt /app/keys/ca.crt
#COPY Skytronsystem/keys/private_key.pem /app/keys/private_key.pem
#COPY Skytronsystem/keys/public_key.pem /app/keys/public_key.pem

# Copy your Django project files into the container
COPY . /app

# (Optional) If you need to collect static files, uncomment the line below:
#RUN python manage.py collectstatic --noinput

# Expose port 2000
#EXPOSE 5001

# Environment variables will be passed from system environment
ARG MAIL_ID
ARG MAIL_PW
ARG DEBUG
ARG SECRET_KEY
ARG EMAIL_HOST_USER
ARG EMAIL_HOST_PASSWORD
ARG ALLOWED_HOSTS
ARG DB_NAME
ARG DB_USER
ARG DB_PASSWORD
ARG DB_HOST
ARG DB_PORT

ENV MAIL_ID=${MAIL_ID}
ENV MAIL_PW=${MAIL_PW}
ENV DEBUG=${DEBUG}
ENV SECRET_KEY=${SECRET_KEY}
ENV EMAIL_HOST_USER=${EMAIL_HOST_USER}
ENV EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
ENV ALLOWED_HOSTS=${ALLOWED_HOSTS}
ENV DB_NAME=${DB_NAME}
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_HOST=${DB_HOST}
ENV DB_PORT=${DB_PORT}
# 


# Run the MQTT client
CMD ["python", "mqttClienttrack.py"]
