# Start from an official Python image - using bullseye instead of buster
FROM python:3.9-slim-bullseye

# Install required system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    wkhtmltopdf libmagic1 \          
    libssl-dev \          
    libffi-dev \    
    build-essential \     
    && rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /app


# Create keys directory first
RUN mkdir -p /app/keys

# Copy certificate files - they are required for the MQTT client
COPY keys/ca.crt /app/keys/ca.crt
#COPY Skytronsystem/keys/private_key.pem /app/keys/private_key.pem
#COPY Skytronsystem/keys/public_key.pem /app/keys/public_key.pem

# Copy your Django project files into the container
COPY . /app

# Copy requirements file
COPY requirements.txt /app/requirements.txt

# Install Python dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
# (Optional) If you need to collect static files, uncomment the line below:
#RUN python manage.py collectstatic --noinput

# Expose port 2000
#EXPOSE 5001

# Environment variables will be passed from system environment
ARG MAIL_ID
ARG MAIL_PW
ARG DEBUG
ARG SECRET_KEY
ARG EMAIL_HOST_USER
ARG EMAIL_HOST_PASSWORD
ARG ALLOWED_HOSTS
ARG DB_NAME
ARG DB_USER
ARG DB_PASSWORD
ARG DB_HOST
ARG DB_PORT
ARG MQTT_BROKER_HOST
ARG MQTT_BROKER_PORT
ARG MQTT_ADMIN_USER
ARG MQTT_ADMIN_PASS
ARG MQTT_USERNAME
ARG MQTT_PASSWORD
ARG SMS_URL
ARG SMS_USERID
ARG SMS_PASSWORD
ARG SMS_SENDER
ARG SMS_PEID
ARG ROOT_URL
ARG JWT_SECRET_KEY
ARG JWT_ALGORITHM
ARG JWT_ACCESS_TOKEN_LIFETIME
ARG JWT_REFRESH_TOKEN_LIFETIME

ENV MAIL_ID=${MAIL_ID}
ENV MAIL_PW=${MAIL_PW}
ENV DEBUG=${DEBUG}
ENV SECRET_KEY=${SECRET_KEY}
ENV EMAIL_HOST_USER=${EMAIL_HOST_USER}
ENV EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
ENV ALLOWED_HOSTS=${ALLOWED_HOSTS}
ENV DB_NAME=${DB_NAME}
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_HOST=${DB_HOST}
ENV DB_PORT=${DB_PORT}
ENV MQTT_BROKER_HOST=${MQTT_BROKER_HOST}
ENV MQTT_BROKER_PORT=${MQTT_BROKER_PORT}
ENV MQTT_ADMIN_USER=${MQTT_ADMIN_USER}
ENV MQTT_ADMIN_PASS=${MQTT_ADMIN_PASS}
ENV MQTT_USERNAME=${MQTT_USERNAME}
ENV MQTT_PASSWORD=${MQTT_PASSWORD}
ENV SMS_URL=${SMS_URL}
ENV SMS_USERID=${SMS_USERID}
ENV SMS_PASSWORD=${SMS_PASSWORD}
ENV SMS_SENDER=${SMS_SENDER}
ENV SMS_PEID=${SMS_PEID}
ENV ROOT_URL=${ROOT_URL}
ENV JWT_SECRET_KEY=${JWT_SECRET_KEY}
ENV JWT_ALGORITHM=${JWT_ALGORITHM}
ENV JWT_ACCESS_TOKEN_LIFETIME=${JWT_ACCESS_TOKEN_LIFETIME}
ENV JWT_REFRESH_TOKEN_LIFETIME=${JWT_REFRESH_TOKEN_LIFETIME}
# 


# Run the MQTT client
CMD ["python", "mqttClienttrack.py"]
