[req]
default_bits = 4096
prompt = no
default_md = sha256
distinguished_name = dn

[dn]
C=IN
ST=Assam
L=Guwahati
O=SKYTRON
OU=Certificate Authority
CN=SKYTRON Intermediate CA

[v3_intermediate_ca]
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer
basicConstraints = critical,CA:TRUE,pathlen:0
keyUsage = critical,digitalSignature,cRLSign,keyCertSign
