# Generated by Django 4.2.9 on 2024-01-11 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceModel', models.IntegerField(verbose_name='Device Model')),
                ('status', models.CharField(max_length=255, verbose_name='Status')),
                ('softwareLatestVersion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Software Latest Version')),
                ('vehicle', models.IntegerField(verbose_name='Vehicle')),
                ('createdby', models.CharField(max_length=255, verbose_name='Created By')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceModel', models.CharField(max_length=255, verbose_name='Device Model')),
                ('status', models.CharField(choices=[('active', 'Active'), ('discontinued', 'Discontinued')], max_length=20, verbose_name='Status')),
                ('hardwareVersion', models.CharField(max_length=255, verbose_name='Hardware Version')),
                ('softwareLatestVersion', models.CharField(max_length=255, verbose_name='Software Latest Version')),
                ('createdby', models.CharField(max_length=255, verbose_name='Created By')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='EditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('type', models.CharField(choices=[('owner', 'Owner'), ('device', 'Device'), ('vehicle', 'Vehicle'), ('devicemodel', 'Device Model'), ('retailer', 'Retailer'), ('manufacturer', 'Manufacturer')], max_length=20, verbose_name='Type')),
                ('from_user', models.IntegerField(verbose_name='From User')),
                ('to_user', models.IntegerField(verbose_name='To User')),
                ('otp', models.IntegerField(verbose_name='OTP')),
                ('newdataid', models.IntegerField(verbose_name='New Data ID')),
                ('olddataid', models.IntegerField(verbose_name='Old Data ID')),
                ('status', models.CharField(choices=[('requestsent', 'Request Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='FOTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceMode', models.IntegerField(verbose_name='Device Mode')),
                ('status', models.CharField(choices=[('active', 'Active'), ('notactive', 'Not Active')], max_length=10, verbose_name='Status')),
                ('softwareVersion', models.CharField(max_length=255, verbose_name='Software Version')),
                ('firmwarePath', models.CharField(max_length=255, verbose_name='Firmware Path')),
                ('firmwareHex', models.CharField(max_length=255, verbose_name='Firmware Hex')),
                ('createdby', models.CharField(max_length=255, verbose_name='Created By')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('address_pin', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Pin')),
                ('gstnnumber', models.CharField(blank=True, max_length=255, null=True, verbose_name='GSTN Number')),
                ('users', models.JSONField(default=list, verbose_name='Users')),
                ('deviceModel', models.JSONField(default=list, verbose_name='Device Model')),
                ('retailer', models.JSONField(default=list, verbose_name='Retailer')),
                ('createdby', models.CharField(max_length=255, verbose_name='Created By')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('Access', models.JSONField(default=list, verbose_name='Access')),
            ],
        ),
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otpTime', models.DateTimeField(auto_now_add=True, verbose_name='OTP Time')),
                ('type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=5, verbose_name='Type')),
                ('user', models.IntegerField(verbose_name='User')),
                ('otp', models.CharField(max_length=255, verbose_name='OTP')),
                ('status', models.CharField(choices=[('otpsent', 'OTP Sent'), ('errorsending', 'Error Sending'), ('verified', 'Verified'), ('donotmatch', 'Do Not Match'), ('timeout', 'Timeout')], max_length=20, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('address_pin', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Pin')),
                ('gstnnumber', models.CharField(blank=True, max_length=255, null=True, verbose_name='GSTN Number')),
                ('users', models.JSONField(default=list, verbose_name='Users')),
                ('createdby', models.CharField(max_length=255, verbose_name='Created By')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('Access', models.JSONField(default=list, verbose_name='Access')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Login Time')),
                ('user', models.IntegerField(verbose_name='User')),
                ('token', models.CharField(max_length=255, verbose_name='Token')),
                ('otp', models.IntegerField(blank=True, null=True, verbose_name='OTP')),
                ('status', models.CharField(choices=[('otpsent', 'OTP Sent'), ('login', 'Login'), ('logout', 'Logout'), ('timeout', 'Timeout')], max_length=10, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velid_time', models.DateTimeField(auto_now_add=True, verbose_name='Valid Time')),
                ('type', models.CharField(max_length=255, verbose_name='Type')),
                ('createdby', models.CharField(max_length=255, verbose_name='Created By')),
                ('settingsstring', models.CharField(max_length=255, verbose_name='Settings String')),
                ('settingsmethod', models.CharField(max_length=255, verbose_name='Settings Method')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('address_pin', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Pin')),
                ('mobile', models.CharField(max_length=15, unique=True, verbose_name='Mobile')),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('stateadmin', 'State Admin'), ('devicemanufacture', 'Device Manufacture'), ('dealer', 'Dealer'), ('owner', 'Owner'), ('filment', 'Filment'), ('sosadmin', 'SOS Admin'), ('teamleader', 'Team Leader'), ('sosexecutive', 'SOS Executive')], max_length=20, verbose_name='Role')),
                ('usertype', models.CharField(default='main', max_length=10, verbose_name='User Type')),
                ('roleassign', models.JSONField(default=list, verbose_name='Role Assign')),
                ('parent', models.CharField(blank=True, max_length=255, null=True, verbose_name='Parent')),
                ('stateid', models.CharField(blank=True, max_length=255, null=True, verbose_name='State ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], max_length=10, verbose_name='Status')),
                ('dob', models.CharField(blank=True, max_length=255, null=True, verbose_name='Date of Birth')),
                ('panfile', models.CharField(blank=True, max_length=255, null=True, verbose_name='PAN File')),
                ('kyctype', models.CharField(blank=True, max_length=255, null=True, verbose_name='KYC Type')),
                ('kycdocnumber', models.CharField(blank=True, max_length=255, null=True, verbose_name='KYC Doc Number')),
                ('kycfile', models.CharField(blank=True, max_length=255, null=True, verbose_name='KYC File')),
                ('mobileotp', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobile OTP')),
                ('mobileotpsend', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobile OTP Send')),
                ('token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token')),
                ('gstnnumber', models.CharField(blank=True, max_length=255, null=True, verbose_name='GSTN Number')),
                ('createdby', models.CharField(max_length=255, verbose_name='Created By')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('Access', models.JSONField(default=list, verbose_name='Access')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], max_length=10, verbose_name='Status')),
                ('access', models.JSONField(default=list, verbose_name='Access')),
                ('vregno', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vehicle Registration Number')),
                ('engineno', models.CharField(blank=True, max_length=255, null=True, verbose_name='Engine Number')),
                ('chessisno', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chassis Number')),
                ('vehiclemake', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vehicle Make')),
                ('vehiclemodel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vehicle Model')),
                ('vehiclecategory', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vehicle Category')),
                ('rcfilepath', models.CharField(blank=True, max_length=255, null=True, verbose_name='RC File Path')),
                ('owner', models.IntegerField(verbose_name='Owner')),
                ('createdby', models.CharField(max_length=255, verbose_name='Created By')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
    ]
