# Generated by Django 5.2 on 2025-10-24 12:00

import django.db.models.deletion
import django.utils.timezone
import skytron_api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0001_initial'),
    ]

    operations = [
        # Fake migration - these tables already exist in the database
        # We're creating this migration file to match the current database state
    ]
