# Generated by Django 4.1.13 on 2024-08-25 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='655a6bdfcb3241f4b72fcb07e93600c3', max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('name', models.CharField(max_length=55)),
                ('phone_no', models.CharField(max_length=55)),
                ('license_no', models.CharField(max_length=55)),
                ('photo', models.CharField(max_length=555, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createby_USERdriver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='devicetag',
            name='drivers',
            field=models.ManyToManyField(blank=True, null=True, related_name='driver_vehicles', to='skytron_api.driver'),
        ),
    ]
