# Generated by Django 5.2 on 2025-05-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='552347aaa62c4b2e92522876b137f470', max_length=32, unique=True),
        ),
    ]
