# Generated by Django 4.2.9 on 2024-04-02 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0001_initial'),
    ]

    operations = [
    ]
