# Generated by Django 4.1.13 on 2024-07-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='82051c47ec214e2db901b91b8683d4ee', max_length=32, unique=True),
        ),
    ]
