# Generated by Django 4.2.9 on 2024-01-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='aaaaaa', max_length=100),
            preserve_default=False,
        ),
    ]
