# Generated by Django 4.1.13 on 2025-04-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='3d72dadad283487ba24a03fd8245c690', max_length=32, unique=True),
        ),
    ]
