# Generated by Django 4.2.9 on 2024-04-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0002_auto_20240402_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyCall',
            fields=[
                ('call_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_imei', models.CharField(max_length=15)),
                ('vehicle_no', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('desk_executive_id', models.CharField(max_length=50)),
                ('field_executive_id', models.CharField(max_length=50)),
                ('final_comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GPSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('start_character', models.CharField(max_length=1)),
                ('header', models.CharField(max_length=1)),
                ('vendor_id', models.CharField(max_length=4)),
                ('firmware_version', models.CharField(max_length=5)),
                ('packet_type', models.CharField(max_length=2)),
                ('alert_id', models.CharField(max_length=2)),
                ('packet_status', models.CharField(max_length=1)),
                ('imei', models.CharField(max_length=15)),
                ('vehicle_registration_number', models.CharField(max_length=16)),
                ('gps_status', models.CharField(max_length=1)),
                ('date', models.CharField(max_length=8)),
                ('time', models.CharField(max_length=6)),
                ('latitude', models.FloatField()),
                ('latitude_dir', models.CharField(max_length=1)),
                ('longitude', models.FloatField()),
                ('longitude_dir', models.CharField(max_length=1)),
                ('speed', models.FloatField()),
                ('heading', models.FloatField()),
                ('satellites', models.IntegerField()),
                ('altitude', models.IntegerField()),
                ('pdop', models.FloatField()),
                ('hdop', models.FloatField()),
                ('network_operator', models.CharField(max_length=8)),
                ('ignition_status', models.CharField(max_length=1)),
                ('main_power_status', models.CharField(max_length=1)),
                ('main_input_voltage', models.FloatField()),
                ('internal_battery_voltage', models.FloatField()),
                ('emergency_status', models.CharField(max_length=1)),
                ('box_tamper_alert', models.CharField(max_length=1)),
                ('gsm_signal_strength', models.CharField(max_length=2)),
                ('mcc', models.CharField(max_length=3)),
                ('mnc', models.CharField(max_length=3)),
                ('lac', models.CharField(max_length=3)),
                ('cell_id', models.CharField(max_length=4)),
                ('nbr1_cell_id', models.CharField(max_length=4)),
                ('nbr1_lac', models.CharField(max_length=4)),
                ('nbr1_signal_strength', models.CharField(max_length=2)),
                ('nbr2_cell_id', models.CharField(max_length=4)),
                ('nbr2_lac', models.CharField(max_length=4)),
                ('nbr2_signal_strength', models.CharField(max_length=2)),
                ('nbr3_cell_id', models.CharField(max_length=4)),
                ('nbr3_lac', models.CharField(max_length=4)),
                ('nbr3_signal_strength', models.CharField(max_length=2)),
                ('nbr4_cell_id', models.CharField(max_length=4)),
                ('nbr4_lac', models.CharField(max_length=4)),
                ('nbr4_signal_strength', models.CharField(max_length=2)),
                ('digital_input_status', models.CharField(max_length=4)),
                ('digital_output_status', models.CharField(max_length=2)),
                ('frame_number', models.IntegerField()),
                ('odometer', models.FloatField()),
                ('checksum', models.CharField(max_length=8)),
                ('end_char', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='GPSDataLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Emergency', 'Emergency'), ('Assistance', 'Assistance')], max_length=20)),
                ('field_ex', models.CharField(max_length=50, unique=True)),
                ('loc_lat', models.CharField(blank=True, max_length=20, null=True)),
                ('loc_lon', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
