# Generated by Django 4.1.13 on 2024-12-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0002_alter_captcha_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertslog',
            name='district',
        ),
        migrations.RemoveField(
            model_name='alertslog',
            name='dummnyuser',
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='080b04447af84faeabf5b77f0d158785', max_length=32, unique=True),
        ),
    ]
