# Generated by Django 4.1.13 on 2024-07-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0002_alter_captcha_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpsdata',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='gpsdata',
            name='end_char',
        ),
        migrations.RemoveField(
            model_name='gpsdata',
            name='firmware_version',
        ),
        migrations.RemoveField(
            model_name='gpsdata',
            name='header',
        ),
        migrations.RemoveField(
            model_name='gpsdata',
            name='imei',
        ),
        migrations.RemoveField(
            model_name='gpsdata',
            name='packet_type',
        ),
        migrations.RemoveField(
            model_name='gpsdata',
            name='vehicle_registration_number',
        ),
        migrations.RemoveField(
            model_name='gpsdata',
            name='vendor_id',
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='6622532310f6491da6909c2b2264226d', max_length=32, unique=True),
        ),
    ]
