# Generated by Django 4.1.13 on 2024-08-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0002_alter_captcha_key_driver_devicetag_drivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='d15f7d5bb1274e34bebac6581ab375f8', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
