# Generated by Django 4.1.13 on 2025-04-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0002_alter_captcha_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='9dd902e77cdc4db78edf8d7a40d9e34e', max_length=32, unique=True),
        ),
    ]
