# Generated by Django 4.1.13 on 2024-09-01 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0003_alter_captcha_key_alter_driver_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='esimprovider',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skytron_api.settings_state'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='51dbef8033674694af8c16d894242f2a', max_length=32, unique=True),
        ),
    ]
