# Generated by Django 4.1.13 on 2024-07-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0003_remove_gpsdata_checksum_remove_gpsdata_end_char_and_more'),
    ]

    operations = [
    ]
