# Generated by Django 4.2.9 on 2024-04-13 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0003_emergencycall_gpsdata_gpsdatalog_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], max_length=20)),
                ('rout', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.device')),
            ],
        ),
    ]
