# Generated by Django 4.1.13 on 2025-04-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0003_alter_captcha_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLogaaaaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=70)),
                ('system_info', models.TextField()),
                ('request_url', models.URLField()),
                ('request_type', models.CharField(max_length=100)),
                ('headers', models.TextField()),
                ('incoming_data', models.TextField()),
                ('response_type', models.CharField(max_length=100)),
                ('error_code', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='6825dfc2b91f4c69b24fcbb877fd25a7', max_length=32, unique=True),
        ),
    ]
