# Generated by Django 4.1.13 on 2024-12-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0003_remove_alertslog_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='2ad51cf5f7b448bc9cdc0715e6d2f47a', max_length=32, unique=True),
        ),
    ]
