# Generated by Django 4.2.9 on 2024-01-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0004_user_companyname_alter_user_password_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kycfile',
            field=models.FileField(blank=True, null=True, upload_to='kyc_files/', verbose_name='KYC File'),
        ),
    ]
