# Generated by Django 4.1.13 on 2024-07-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0004_rename_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='2b91d150e1ec4f84883e90a1968d2b62', max_length=32, unique=True),
        ),
    ]
