# Generated by Django 4.1.13 on 2024-09-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0004_esimprovider_state_alter_captcha_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='37bcf0a26e9d4233ba3bed7bb5f0e87d', max_length=32, unique=True),
        ),
    ]
