# Generated by Django 4.2.9 on 2024-04-13 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0004_rout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rout',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.devicestock'),
        ),
    ]
