# Generated by Django 4.1.13 on 2024-09-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0005_alter_captcha_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rout',
            new_name='Route',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='rout',
            new_name='route',
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='fab2ca6744b34cf8b3324bc8926f5024', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='devicetag',
            name='status',
            field=models.CharField(choices=[('Dealer_OTP_Sent', 'Dealer OTP Sent'), ('Dealer_OTP_Verified', 'Dealer_OTP_Verified'), ('TempActive', 'TempActive'), ('Owner_OTP_Sent', 'Owner OTP Sent'), ('Owner_OTP_Verified', 'Owner OTP Verified'), ('RegNo_Configuration_SentToDevice', 'Reg No Configuration Sent to Device'), ('RegNo_Configuration_Confirmed', 'Reg No Configuration Confirmed'), ('Live_Location_Confirmed', 'Live Location Confirmed'), ('SOS_Confirmed', 'SOS Confirmed'), ('Device_Active', 'Device Active'), ('Device_Not_Active', 'Device Not Active'), ('Device_Untagged', 'Device Untagged'), ('TagDeleted', 'TagDeleted')], max_length=255),
        ),
    ]
