# Generated by Django 4.2.9 on 2024-01-18 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0005_alter_user_kycfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='name',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='company_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Company Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='document_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='document_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='device',
            name='deviceModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.devicemodel'),
        ),
        migrations.AlterField(
            model_name='device',
            name='softwareLatestVersion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('FactoryTestOK', 'FactoryTestOK'), ('ShipedtoRetailer', 'ShipedtoRetailer'), ('Sold', 'Sold'), ('Installed', 'Installed'), ('Active', 'Active'), ('DeviceError', 'Device Error'), ('Discontinued', 'Discontinued')], max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='vehicle',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='softwareLatestVersion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('discontinued', 'Discontinued')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='Access',
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='address_pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='deviceModel',
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='gstnnumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='retailer',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='users',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='Access',
        ),
        migrations.AlterField(
            model_name='retailer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='address_pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='gstnnumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='users',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='access',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='chessisno',
            field=models.CharField(default='1111', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engineno',
            field=models.CharField(default=1231313, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='rcfilepath',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehiclecategory',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehiclemake',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehiclemodel',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vregno',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='Access',
            field=models.ManyToManyField(blank=True, related_name='manufacturer_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='deviceModel',
            field=models.ManyToManyField(blank=True, related_name='manufacturers', to='skytron_api.devicemodel'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='retailer',
            field=models.ManyToManyField(blank=True, related_name='manufacturers', to='skytron_api.retailer'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='users',
            field=models.ManyToManyField(related_name='manufacturers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retailer',
            name='Access',
            field=models.ManyToManyField(blank=True, related_name='retailer_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retailer',
            name='users',
            field=models.ManyToManyField(related_name='retailers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='access',
            field=models.ManyToManyField(blank=True, related_name='accessible_vehicles', to=settings.AUTH_USER_MODEL),
        ),
    ]
