# Generated by Django 4.2.9 on 2024-04-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0005_alter_rout_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=3)),
                ('device_imei', models.CharField(max_length=15)),
                ('packet_status', models.CharField(max_length=2)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('gps_validity', models.CharField(max_length=1)),
                ('latitude', models.FloatField()),
                ('latitude_direction', models.CharField(max_length=1)),
                ('longitude', models.FloatField()),
                ('longitude_direction', models.CharField(max_length=1)),
                ('altitude', models.FloatField()),
                ('speed', models.FloatField()),
                ('distance', models.FloatField()),
                ('provider', models.CharField(max_length=50)),
                ('vehicle_reg_no', models.CharField(max_length=20)),
                ('reply_mob_no', models.CharField(max_length=15)),
            ],
        ),
    ]
