# Generated by Django 4.1.13 on 2024-07-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0006_rename_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='ed04a1cf883c4d2fa75b917eb1da4c59', max_length=32, unique=True),
        ),
    ]
