# Generated by Django 4.2.9 on 2024-02-05 08:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0006_remove_manufacturer_name_manufacturer_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cop_no', models.CharField(max_length=255)),
                ('cop_validity', models.DateField()),
                ('created_by', models.IntegerField()),
                ('created', models.DateField()),
                ('valid', models.BooleanField()),
                ('status', models.CharField(choices=[('Manufacturer_OTP_Sent', 'Manufacturer OTP Sent'), ('Manufacturer_OTP_Verified', 'Manufacturer OTP Verified'), ('StateAdminOTPSend', 'State Admin OTP Sent'), ('StateAdminApproved', 'State Admin Approved')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_esn', models.CharField(max_length=255)),
                ('iccid', models.CharField(max_length=255)),
                ('imei', models.CharField(max_length=255)),
                ('telecom_provider1', models.CharField(max_length=255)),
                ('telecom_provider2', models.CharField(max_length=255)),
                ('msisdn1', models.CharField(max_length=255)),
                ('msisdn2', models.CharField(max_length=255)),
                ('imsi1', models.CharField(max_length=255)),
                ('imsi2', models.CharField(max_length=255)),
                ('eSim_validity', models.DateField()),
                ('eSim_provider', models.CharField(max_length=255)),
                ('remarks', models.TextField()),
                ('created', models.DateField()),
                ('created_by', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_owner', models.IntegerField()),
                ('vehicle_reg_no', models.CharField(max_length=255)),
                ('engine_no', models.CharField(max_length=255)),
                ('chassis_no', models.CharField(max_length=255)),
                ('vehicle_make', models.CharField(max_length=255)),
                ('vehicle_model', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('rc_file', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Dealer_OTP_Sent', 'Dealer OTP Sent'), ('Dealer_OTP_Verified', 'Dealer OTP Verified'), ('Owner_OTP_Sent', 'Owner OTP Sent'), ('Owner_OTP_Verified', 'Owner OTP Verified'), ('RegNo_Configuration_SentToDevice', 'Reg No Configuration Sent to Device'), ('RegNo_Configuration_Confirmed', 'Reg No Configuration Confirmed'), ('Live_Location_Confirmed', 'Live Location Confirmed'), ('SOS_Confirmed', 'SOS Confirmed'), ('Device_Active', 'Device Active'), ('Device_Not_Active', 'Device Not Active'), ('Device_Untagged', 'Device Untagged')], max_length=255)),
                ('tagged_by', models.IntegerField()),
                ('tagged', models.DateField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.devicestock')),
            ],
        ),
        migrations.CreateModel(
            name='IPList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip1', models.GenericIPAddressField()),
                ('port1', models.CharField(max_length=4)),
                ('ip2', models.GenericIPAddressField()),
                ('port2', models.CharField(max_length=4)),
                ('ip_im', models.GenericIPAddressField()),
                ('port_im', models.CharField(max_length=4)),
                ('rule', models.TextField()),
                ('status', models.CharField(choices=[('Valid', 'Valid')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StockAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer', models.IntegerField()),
                ('assigned_by', models.IntegerField()),
                ('assigned', models.DateField()),
                ('shipping_remark', models.TextField()),
                ('stock_status', models.CharField(choices=[('In_transit_to_dealer', 'In Transit to Dealer'), ('Available_for_fitting', 'Available for Fitting'), ('Fitted', 'Fitted'), ('ESIM_Active_Req_Sent', 'ESIM Active Request Sent'), ('ESIM_Active_Confirmed', 'ESIM Active Confirmed'), ('IP_PORT_Configured', 'IP Port Configured'), ('SOS_GATEWAY_NO_Configured', 'SOS Gateway No Configured'), ('SMS_GATEWAY_NO_Configured', 'SMS Gateway No Configured'), ('Device_Defective', 'Device Defective'), ('Returned_to_manufacturer', 'Returned to Manufacturer')], max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.devicestock')),
            ],
        ),
        migrations.DeleteModel(
            name='Tracking',
        ),
        migrations.DeleteModel(
            name='TrackingLog',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='createdby',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='deviceModel',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='hardwareVersion',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='softwareLatestVersion',
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='created_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='hardware_version',
            field=models.CharField(default='1.1.1.1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='model_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='tac_doc_path',
            field=models.FileField(blank=True, null=True, upload_to='tac_docs/'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='tac_no',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='tac_validity',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='test_agency',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='vendor_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='status',
            field=models.CharField(choices=[('Manufacturer_OTP_Sent', 'Manufacturer OTP Sent'), ('Manufacturer_OTP_Verified', 'Manufacturer OTP Verified'), ('StateAdminOTPSend', 'State Admin OTP Sent'), ('StateAdminApproved', 'State Admin Approved')], max_length=255),
        ),
        migrations.AddField(
            model_name='devicestock',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.devicemodel'),
        ),
        migrations.AddField(
            model_name='devicecop',
            name='device_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.devicemodel'),
        ),
    ]
