# Generated by Django 4.1.13 on 2024-09-05 05:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0006_rename_rout_route_rename_rout_route_route_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('mobile', models.CharField(max_length=15, unique=True, verbose_name='Mobile')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('otp', models.CharField(default='123456', max_length=100)),
                ('otp_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('em_contact', models.CharField(max_length=15, unique=True, verbose_name='em_contact')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('online', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='ce36bd042e4740049efcf881a4272f09', max_length=32, unique=True),
        ),
    ]
