# Generated by Django 4.2.9 on 2024-05-01 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0006_gpslocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Route_in', 'Route_in'), ('Route_out', 'Route_out'), ('Em_in', 'Em_in'), ('Em_out', 'Em_out'), ('Eng_on', 'Eng_on'), ('Eng_off', 'Eng_off'), ('OverSpeed_in', 'OverSpeed_in'), ('OverSpeed_out', 'OverSpeed_out'), ('LowIntBat_in', 'LowIntBat_in'), ('LowIntBat_out', 'LowIntBat_out'), ('LowExtBat_in', 'LowExtBat_in'), ('LowExtBat_out', 'LowExtBat_out'), ('ExtBatDiscnt_in', 'ExtBatDiscnt_in'), ('ExtBatDiscnt_out', 'ExtBatDiscnt_out'), ('BoxTemp_in', 'BoxTemp_in'), ('BoxTemp_out', 'BoxTemp_out'), ('EmTemp_in', 'EmTemp_in'), ('EmTemp_out', 'EmTemp_out'), ('Tilt_in', 'Tilt_in'), ('Tilt_out', 'Tilt_out'), ('HarshBreak', 'HarshBreak'), ('HarshTurn', 'HarshTurn'), ('HarshAccileration', 'HarshAccileration')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('deviceTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.devicetag')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.dto_rto')),
                ('em_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skytron_api.emergencycall')),
                ('gps_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.gpsdata')),
                ('route_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skytron_api.rout')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.stateadmin')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.vehicle')),
            ],
        ),
    ]
