# Generated by Django 4.1.13 on 2024-09-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0007_tempuser_alter_captcha_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='a193e6eaf16b4fdfbed954d1815e8ac2', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='em_contact',
            field=models.CharField(max_length=15, verbose_name='em_contact'),
        ),
    ]
