# Generated by Django 4.1.13 on 2024-07-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0007_alter_captcha_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='9f1cc562ef064b7687569621ffbb6673', max_length=32, unique=True),
        ),
    ]
