# Generated by Django 4.2.9 on 2024-05-01 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0007_allertlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllertLog',
            new_name='AlertsLog',
        ),
    ]
