# Generated by Django 4.2.9 on 2024-02-06 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0007_devicecop_devicestock_devicetag_iplist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecop',
            name='cop_file',
            field=models.FileField(blank=True, null=True, upload_to='cop_files/'),
        ),
        migrations.AddField(
            model_name='devicecop',
            name='latest',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='devicecop',
            name='valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='iplist',
            name='rule',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='iplist',
            name='status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stockassignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockassignment',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.retailer'),
        ),
        migrations.AlterField(
            model_name='stockassignment',
            name='shipping_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockassignment',
            name='stock_status',
            field=models.CharField(max_length=255),
        ),
    ]
