# Generated by Django 4.2.9 on 2024-02-06 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0008_devicecop_cop_file_devicecop_latest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetag',
            name='vehicle_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
