# Generated by Django 4.1.13 on 2024-09-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0008_alter_captcha_key_alter_tempuser_em_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='ble_key',
            field=models.CharField(default='q', max_length=15, unique=True, verbose_name='ble_key'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempuser',
            name='session_key',
            field=models.CharField(default='q', max_length=100, unique=True, verbose_name='session_key'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='cd3113b6621c4f609bcf6aa4e72db558', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='mobile',
            field=models.CharField(max_length=15, verbose_name='Mobile'),
        ),
    ]
