# Generated by Django 4.1.13 on 2024-07-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0008_alter_captcha_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpsdata',
            name='start_character',
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='82678f8b2f5847baa8c89e8d13638d94', max_length=32, unique=True),
        ),
    ]
