# Generated by Django 4.1.13 on 2024-07-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0009_remove_gpsdata_start_character_alter_captcha_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='753de5dd983f42eba0b43a2491b54e2f', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='lac',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='mcc',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='mnc',
            field=models.CharField(max_length=4),
        ),
    ]
