# Generated by Django 4.2.9 on 2024-02-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0009_alter_devicetag_vehicle_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicestock',
            old_name='eSim_provider',
            new_name='esim_provider',
        ),
        migrations.RenameField(
            model_name='devicestock',
            old_name='eSim_validity',
            new_name='esim_validity',
        ),
        migrations.AlterField(
            model_name='devicestock',
            name='imsi2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='devicestock',
            name='msisdn2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='devicestock',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicestock',
            name='telecom_provider2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='iplist',
            name='rule',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='iplist',
            name='status',
            field=models.CharField(choices=[('Valid', 'Valid')], max_length=255),
        ),
        migrations.AlterField(
            model_name='stockassignment',
            name='shipping_remark',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockassignment',
            name='stock_status',
            field=models.CharField(choices=[('In_transit_to_dealer', 'In Transit to Dealer'), ('Available_for_fitting', 'Available for Fitting'), ('Fitted', 'Fitted'), ('ESIM_Active_Req_Sent', 'ESIM Active Request Sent'), ('ESIM_Active_Confirmed', 'ESIM Active Confirmed'), ('IP_PORT_Configured', 'IP Port Configured'), ('SOS_GATEWAY_NO_Configured', 'SOS Gateway No Configured'), ('SMS_GATEWAY_NO_Configured', 'SMS Gateway No Configured'), ('Device_Defective', 'Device Defective'), ('Returned_to_manufacturer', 'Returned to Manufacturer')], max_length=255),
        ),
    ]
