# Generated by Django 4.2.9 on 2024-05-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0009_alter_session_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetag',
            name='receipt_file_or',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicetag',
            name='receipt_file_ul',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
