# Generated by Django 4.1.13 on 2024-09-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0009_tempuser_ble_key_tempuser_session_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='b02c94a2cab749eba4de0148a6353349', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='ble_key',
            field=models.CharField(max_length=15, verbose_name='ble_key'),
        ),
    ]
