# Generated by Django 4.2.9 on 2024-05-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0010_devicetag_receipt_file_or_devicetag_receipt_file_ul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dto_rto',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sos_ex',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sos_user',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
