# Generated by Django 4.1.13 on 2024-09-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0010_alter_captcha_key_alter_tempuser_ble_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='em_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='em_lat'),
        ),
        migrations.AddField(
            model_name='tempuser',
            name='em_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='em_lon'),
        ),
        migrations.AddField(
            model_name='tempuser',
            name='em_msg',
            field=models.TextField(blank=True, null=True, verbose_name='em_msg'),
        ),
        migrations.AddField(
            model_name='tempuser',
            name='em_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tempuser',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='feedback'),
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='9e8673e50ca5480ea1f9fb70590959e2', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='ble_key',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ble_key'),
        ),
    ]
