# Generated by Django 4.1.13 on 2024-07-26 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('skytron_api', '0010_alter_captcha_key_alter_gpsdata_lac_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('is_active', models.BooleanField(default=False)),
                ('last_activity', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('authtoken.token',),
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='377c2eea33f44614a6e8408cd627ec88', max_length=32, unique=True),
        ),
    ]
