# Generated by Django 4.2.9 on 2024-06-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0011_alter_dto_rto_district_alter_sos_ex_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sms_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_text', models.CharField(max_length=500)),
                ('no', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Processed', 'Processed'), ('Error', 'Error')], max_length=20)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='sms_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_text', models.CharField(max_length=500)),
                ('no', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Queue', 'Queue'), ('Sent', 'Sent'), ('Error', 'Error')], max_length=20)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
