# Generated by Django 4.1.13 on 2024-07-28 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0011_customtoken_alter_captcha_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertslog',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.settings_state'),
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='ca251463a84a4a27af6dadfe710ad513', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='settings_district',
            name='district',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='settings_district',
            name='district_code',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='settings_state',
            name='state',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
