# Generated by Django 4.2.9 on 2024-02-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0011_alter_devicecop_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestock',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
