# Generated by Django 4.1.13 on 2024-07-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0012_alter_alertslog_state_alter_captcha_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='c24b46cec6b74ec594af415124912cf6', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='chessisno',
            field=models.CharField(max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engineno',
            field=models.CharField(max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehiclecategory',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehiclemake',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehiclemodel',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vregno',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
