# Generated by Django 4.1.13 on 2024-09-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0012_alter_captcha_key_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='71ec5e00f8d84cf4a3e61484982f5b92', max_length=32, unique=True),
        ),
    ]
