# Generated by Django 4.2.9 on 2024-06-10 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0012_sms_in_sms_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdata',
            name='device_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skytron_api.devicetag'),
        ),
        migrations.AddField(
            model_name='gpslocation',
            name='device_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skytron_api.devicetag'),
        ),
    ]
