# Generated by Django 4.2.9 on 2024-02-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0012_alter_devicestock_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestock',
            name='esim_validity',
            field=models.DateTimeField(),
        ),
    ]
