# Generated by Django 4.2.9 on 2024-06-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0013_gpsdata_device_tag_gpslocation_device_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathCaptcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='sos_ex',
            name='user_type',
            field=models.CharField(choices=[('Team_lead', 'Team_lead'), ('Desk_executive', 'Desk_executive'), ('Field_executive', 'Field_executive')], default='Desk_executive', max_length=20),
            preserve_default=False,
        ),
    ]
