# Generated by Django 4.1.13 on 2024-07-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0013_alter_captcha_key_alter_vehicle_chessisno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='47cc2ccb0175463db240c2488125aadc', max_length=32, unique=True),
        ),
    ]
