# Generated by Django 4.1.13 on 2024-09-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0013_notice_status_alter_captcha_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdata',
            name='packet_type',
            field=models.CharField(default='N', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='6d5678ff32774932b79c4b46f4ca7cc4', max_length=32, unique=True),
        ),
    ]
