# Generated by Django 4.2.9 on 2024-02-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0013_alter_devicestock_esim_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockassignment',
            name='assigned',
            field=models.DateTimeField(),
        ),
    ]
