# Generated by Django 4.2.9 on 2024-02-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0014_alter_stockassignment_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetag',
            name='tagged',
            field=models.DateTimeField(),
        ),
    ]
