# Generated by Django 4.2.9 on 2024-06-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0014_mathcaptcha_sos_ex_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSemDataLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.TextField()),
            ],
        ),
    ]
