# Generated by Django 4.1.13 on 2024-07-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0014_alter_captcha_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='55624b3e26714257a2eadbd616f5cfcd', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='devicetag',
            name='category',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='devicetag',
            name='chassis_no',
            field=models.CharField(max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='devicetag',
            name='engine_no',
            field=models.CharField(max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='devicetag',
            name='vehicle_make',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='devicetag',
            name='vehicle_model',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='devicetag',
            name='vehicle_reg_no',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
