# Generated by Django 4.1.13 on 2024-09-26 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0014_gpsdata_packet_type_alter_captcha_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='start_time')),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('desk_ex_assigned', 'desk_ex_assigned'), ('broadcast_pending', 'broadcast_pending'), ('field_ex_aproaching', 'field_ex_aproaching'), ('field_ex_arrived', 'field_ex_arrived'), ('closed_false_allert', 'closed_false_allert'), ('closed', 'closed')], max_length=30)),
                ('closer_comment', models.TextField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DeviceTag_id', to='skytron_api.devicetag')),
            ],
        ),
        migrations.CreateModel(
            name='EMCallAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='start_time')),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('arriving', 'arriving'), ('arrived', 'arrived'), ('closed_false_allert', 'closed_false_allert'), ('closed', 'closed')], max_length=30)),
                ('type', models.CharField(choices=[('teamlead', 'teamlead'), ('desk_ex', 'desk_ex'), ('police_ex', 'police_ex'), ('ambulance_ex', 'ambulance_ex')], max_length=30)),
                ('closer_comment', models.TextField()),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EMCall_id', to='skytron_api.emcall')),
            ],
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='34904a4ea2fb414b96469693d84f40ee', max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='EMUserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_lat', models.FloatField(blank=True, null=True, verbose_name='em_lat')),
                ('speed', models.FloatField(blank=True, null=True, verbose_name='speed')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='time')),
                ('field_ex', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_executive1_id_location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EMCallMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='time')),
                ('message', models.TextField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EMCallAssignment111_id', to='skytron_api.emcallassignment')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EMCall_id111', to='skytron_api.emcall')),
            ],
        ),
    ]
