# Generated by Django 4.1.13 on 2024-09-28 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0015_emcall_emcallassignment_alter_captcha_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EM_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('expirydate', models.DateField(auto_now_add=True)),
                ('idProofno', models.CharField(blank=True, max_length=255, null=True)),
                ('file_idProof', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('UserVerified', 'UserVerified'), ('StateAdminVerified', 'StateAdminVerified'), ('UserExpired', 'UserExpired'), ('Discontinued', 'Discontinued')], max_length=20)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.settings_state')),
                ('users', models.ManyToManyField(related_name='EM_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EM_ex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('expirydate', models.DateField(auto_now_add=True)),
                ('user_type', models.CharField(choices=[('teamlead', 'teamlead'), ('desk_ex', 'desk_ex'), ('police_ex', 'police_ex'), ('ambulance_ex', 'ambulance_ex'), ('PCR', 'PCR'), ('ACR', 'ACR')], max_length=20)),
                ('idProofno', models.CharField(blank=True, max_length=255, null=True)),
                ('file_idProof', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('UserVerified', 'UserVerified'), ('StateAdminVerified', 'StateAdminVerified'), ('UserExpired', 'UserExpired'), ('Discontinued', 'Discontinued')], max_length=20)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.settings_state')),
                ('users', models.ManyToManyField(related_name='SOS_ex_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EMTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Removed', 'Removed')], max_length=20)),
                ('name', models.TextField()),
                ('detail', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SOS_admin_createdby_team', to='skytron_api.em_admin')),
                ('members', models.ManyToManyField(related_name='SOS_Executive_member_team', to='skytron_api.em_ex')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.settings_state')),
                ('teamlead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.em_ex')),
            ],
        ),
        migrations.RenameModel(
            old_name='GPSLocation',
            new_name='EMGPSLocation',
        ),
        migrations.RemoveField(
            model_name='emergencycall_assignment',
            name='emergencyCall_id',
        ),
        migrations.RemoveField(
            model_name='emergencycall_assignment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='help',
            name='field_ex',
        ),
        migrations.RemoveField(
            model_name='sos_admin',
            name='createdby',
        ),
        migrations.RemoveField(
            model_name='sos_admin',
            name='state',
        ),
        migrations.RemoveField(
            model_name='sos_admin',
            name='users',
        ),
        migrations.RemoveField(
            model_name='sos_ex',
            name='createdby',
        ),
        migrations.RemoveField(
            model_name='sos_ex',
            name='state',
        ),
        migrations.RemoveField(
            model_name='sos_ex',
            name='users',
        ),
        migrations.RemoveField(
            model_name='sos_team',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='sos_team',
            name='createdby',
        ),
        migrations.RemoveField(
            model_name='sos_team',
            name='desk_team',
        ),
        migrations.RemoveField(
            model_name='sos_team',
            name='district',
        ),
        migrations.RemoveField(
            model_name='sos_team',
            name='field_team',
        ),
        migrations.RemoveField(
            model_name='sos_team',
            name='state',
        ),
        migrations.RemoveField(
            model_name='sos_team',
            name='teamlead',
        ),
        migrations.RemoveField(
            model_name='sos_team',
            name='updatedby',
        ),
        migrations.RemoveField(
            model_name='sos_user',
            name='createdby',
        ),
        migrations.RemoveField(
            model_name='sos_user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='sos_user',
            name='users',
        ),
        migrations.AddField(
            model_name='emcallassignment',
            name='accept_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emcallassignment',
            name='arrived_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emcallassignment',
            name='complete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emcallassignment',
            name='desk_ex_comment',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alertslog',
            name='em_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skytron_api.emcall'),
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='6611d70f11f5493683c110461a5c0870', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='emcallassignment',
            name='type',
            field=models.CharField(choices=[('teamlead', 'teamlead'), ('desk_ex', 'desk_ex'), ('police_ex', 'police_ex'), ('ambulance_ex', 'ambulance_ex'), ('pcr', 'pcr'), ('acr', 'acr')], max_length=30),
        ),
        migrations.DeleteModel(
            name='EmergencyCall',
        ),
        migrations.DeleteModel(
            name='EmergencyCall_assignment',
        ),
        migrations.DeleteModel(
            name='Help',
        ),
        migrations.DeleteModel(
            name='SOS_admin',
        ),
        migrations.DeleteModel(
            name='SOS_ex',
        ),
        migrations.DeleteModel(
            name='SOS_team',
        ),
        migrations.DeleteModel(
            name='SOS_user',
        ),
        migrations.AddField(
            model_name='emcall',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EMTeams_id', to='skytron_api.emteams'),
        ),
        migrations.AddField(
            model_name='emcallassignment',
            name='admin',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='emcalladmin', to='skytron_api.em_admin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emcallassignment',
            name='ex',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='exec_id', to='skytron_api.em_ex'),
            preserve_default=False,
        ),
    ]
