# Generated by Django 4.2.9 on 2024-06-16 05:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0015_gpsemdatalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='lastactivity',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='lastactivity'),
        ),
    ]
