# Generated by Django 4.2.9 on 2024-02-15 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0015_alter_devicetag_tagged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='Access',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='address_pin',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='deviceModel',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='document_path',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='retailer',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='Access',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='address_pin',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='document_path',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gstnnumber',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kycdocnumber',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kycfile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kyctype',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobileotp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobileotpsend',
        ),
        migrations.RemoveField(
            model_name='user',
            name='panfile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roleassign',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stateid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='expirydate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='file_GSTCertificate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='file_authLetter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='file_companRegCertificate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='file_idProof',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='gstno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='idProofno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('UserVerified', 'UserVerified'), ('StateAdminVerified', 'StateAdminVerified'), ('UserExpired', 'UserExpired'), ('Discontinued', 'Discontinued')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retailer',
            name='company_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Company Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retailer',
            name='expirydate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retailer',
            name='file_GSTCertificate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='file_authLetter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='file_companRegCertificate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='file_idProof',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='gstno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='idProofno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('UserVerified', 'UserVerified'), ('StateAdminVerified', 'StateAdminVerified'), ('UserExpired', 'UserExpired'), ('Discontinued', 'Discontinued')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='address_State',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address State'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='users',
            field=models.ManyToManyField(related_name='manufacturers_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='users',
            field=models.ManyToManyField(related_name='Retailer_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VehicleOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name')),
                ('created', models.DateField(auto_now_add=True)),
                ('expirydate', models.DateField(auto_now_add=True)),
                ('idProofno', models.CharField(blank=True, max_length=255, null=True)),
                ('file_idProof', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('UserVerified', 'UserVerified'), ('UserExpired', 'UserExpired'), ('Discontinued', 'Discontinued')], max_length=20)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='manufacturers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='eSimProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('gstnnumber', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('expirydate', models.DateField(auto_now_add=True)),
                ('gstno', models.CharField(blank=True, max_length=255, null=True)),
                ('idProofno', models.CharField(blank=True, max_length=255, null=True)),
                ('file_authLetter', models.CharField(blank=True, max_length=255, null=True)),
                ('file_companRegCertificate', models.CharField(blank=True, max_length=255, null=True)),
                ('file_GSTCertificate', models.CharField(blank=True, max_length=255, null=True)),
                ('file_idProof', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('UserVerified', 'UserVerified'), ('StateAdminVerified', 'StateAdminVerified'), ('UserExpired', 'UserExpired'), ('Discontinued', 'Discontinued')], max_length=20)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='eSimProvider_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
