# Generated by Django 4.1.13 on 2024-07-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0015_alter_captcha_key_alter_devicetag_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='e020664f5e744180b4b03994c622b338', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='devicestock',
            name='device_esn',
            field=models.CharField(max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='devicestock',
            name='iccid',
            field=models.CharField(max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='devicestock',
            name='imei',
            field=models.CharField(max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='devicestock',
            name='imsi1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='devicestock',
            name='msisdn1',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='devicestock',
            name='msisdn2',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='devicestock',
            name='telecom_provider1',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='devicestock',
            name='telecom_provider2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
