# Generated by Django 4.2.9 on 2024-06-16 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0016_session_lastactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skytron_api.settings_state'),
            preserve_default=False,
        ),
    ]
