# Generated by Django 4.1.13 on 2024-09-28 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0016_em_admin_em_ex_emteams_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emcallassignment',
            old_name='end_time',
            new_name='reject_time',
        ),
        migrations.AddField(
            model_name='emteams',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emuserlocation',
            name='em_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='em_lon'),
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='ff38d879ee4348c1b1aedd71140a3d73', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='emcallmessages',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EMCallAssignm11ent111_id', to='skytron_api.emcallassignment'),
        ),
        migrations.AlterField(
            model_name='emcallmessages',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EMCa111ll_id111', to='skytron_api.emcall'),
        ),
        migrations.AlterField(
            model_name='emteams',
            name='members',
            field=models.ManyToManyField(null=True, related_name='SOS_Executive_member_team', to='skytron_api.em_ex'),
        ),
        migrations.AlterField(
            model_name='emteams',
            name='status',
            field=models.CharField(choices=[('NotActive', 'NotActive'), ('Active', 'Active'), ('Removed', 'Removed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='emuserlocation',
            name='field_ex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_executive1_id_location', to='skytron_api.em_ex'),
        ),
        migrations.CreateModel(
            name='EMCallBackupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='time')),
                ('type', models.CharField(choices=[('police_ex', 'police_ex'), ('ambulance_ex', 'ambulance_ex')], max_length=30)),
                ('quantity', models.IntegerField()),
                ('accepted', models.BooleanField()),
                ('message', models.TextField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EMCallAssignment111_id', to='skytron_api.emcallassignment')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EMCall_id111', to='skytron_api.emcall')),
            ],
        ),
    ]
