# Generated by Django 4.2.9 on 2024-03-22 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0016_remove_manufacturer_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('stateadmin', 'State Admin'), ('devicemanufacture', 'Device Manufacture'), ('dealer', 'Dealer'), ('owner', 'Owner'), ('esimprovider', 'eSimProvider'), ('filment', 'Filment'), ('sosadmin', 'SOS Admin'), ('teamleader', 'Team Leader'), ('sosexecutive', 'SOS Executive')], max_length=20, verbose_name='Role'),
        ),
    ]
