# Generated by Django 4.1.13 on 2024-07-30 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0016_alter_captcha_key_alter_devicestock_device_esn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='esimActivationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creates_at')),
                ('valid_from', models.DateTimeField(null=True)),
                ('valid_upto', models.DateTimeField(null=True)),
                ('accepted_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('valid', 'valid'), ('invalid', 'invalid')], max_length=20, verbose_name='Status')),
                ('ceated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.retailer')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.device')),
                ('eSim_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.esimprovider')),
            ],
        ),
        migrations.RemoveField(
            model_name='alertslog',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='otp',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='ceb5204e09c2478ab15eb2b4c8324f16', max_length=32, unique=True),
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
