# Generated by Django 4.1.13 on 2024-07-30 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0017_esimactivationrequest_remove_alertslog_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='d01e730a81d74c37affb0d79c83f8747', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='esimactivationrequest',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.devicetag'),
        ),
        migrations.AlterField(
            model_name='esimactivationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('valid', 'valid'), ('invalid', 'invalid')], max_length=20, verbose_name='Status'),
        ),
    ]
