# Generated by Django 4.1.13 on 2024-09-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0017_rename_end_time_emcallassignment_reject_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='7728a4660a7d46ec9db2003135cac492', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='emcall',
            name='closer_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emcallassignment',
            name='closer_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emcallassignment',
            name='desk_ex_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
