# Generated by Django 4.2.9 on 2024-06-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0017_manufacturer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings_district',
            name='district_code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
