# Generated by Django 4.1.13 on 2024-07-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0018_alter_captcha_key_alter_esimactivationrequest_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='058540e1c988440a991457a857283e2b', max_length=32, unique=True),
        ),
    ]
