# Generated by Django 4.2.9 on 2024-03-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0018_alter_devicecop_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecop',
            name='created_by',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='created_by',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devicestock',
            name='created_by',
            field=models.IntegerField(),
        ),
    ]
