# Generated by Django 4.2.9 on 2024-06-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0018_settings_district_district_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='eSimProviders',
            field=models.ManyToManyField(blank=True, related_name='eSimProvider_devicemodle', to='skytron_api.esimprovider'),
        ),
    ]
