# Generated by Django 4.1.13 on 2024-10-03 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0018_alter_captcha_key_alter_emcall_closer_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='976b9c8c603e43499a85351fd076da79', max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='EMCallBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='start_time')),
                ('accept_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_time', models.DateTimeField(blank=True, null=True)),
                ('radius', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('timeout', 'timeout'), ('canceled', 'canceled')], max_length=30)),
                ('type', models.CharField(choices=[('police_ex', 'police_ex'), ('ambulance_ex', 'ambulance_ex'), ('pcr', 'pcr'), ('acr', 'acr')], max_length=30)),
                ('acceted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accptedbyexec_id', to='skytron_api.em_ex')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emcalladminb', to='skytron_api.em_admin')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EMCallb_id', to='skytron_api.emcall')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='createdbyexec_id', to='skytron_api.em_ex')),
            ],
        ),
    ]
