# Generated by Django 4.2.9 on 2024-06-19 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0019_devicemodel_esimproviders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Date of Birth'),
            preserve_default=False,
        ),
    ]
