# Generated by Django 4.1.13 on 2024-07-30 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0019_alter_captcha_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='305843a4ba784da6b0e82eba036cd970', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='esimactivationrequest',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.devicestock'),
        ),
    ]
