# Generated by Django 4.1.13 on 2024-07-30 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0020_alter_captcha_key_alter_esimactivationrequest_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='otp_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='fe22229390684ac19a33214a6948b6e5', max_length=32, unique=True),
        ),
    ]
