# Generated by Django 4.2.17 on 2026-04-05 14:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0021_alertslog_alert_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='BleKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True, verbose_name='BLE Key')),
                ('imei', models.CharField(max_length=15, verbose_name='Device IMEI')),
                ('active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('entry_time', models.DateTimeField(auto_now_add=True, verbose_name='Entry Time')),
            ],
        ),
        migrations.CreateModel(
            name='BusStand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bus_stand',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('image_file', models.CharField(blank=True, max_length=500, null=True)),
                ('vehicle_reg_no', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('police_station', models.CharField(blank=True, max_length=100, null=True)),
                ('latest_status', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'incident_register',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('superadmin', 'Super Admin'), ('stateadmin', 'State Admin'), ('devicemanufacture', 'Device Manufacture'), ('dealer', 'Dealer'), ('owner', 'Owner'), ('esimprovider', 'eSimProvider'), ('filment', 'Filment'), ('sosadmin', 'SOS Admin'), ('teamleader', 'Team Leader'), ('sosexecutive', 'SOS Executive'), ('default', 'Default')], max_length=20, unique=True, verbose_name='User Role')),
                ('daily_login_limit', models.IntegerField(default=0, help_text='Maximum number of logins allowed per day per user. 0 = unlimited', verbose_name='Daily Login Limit')),
                ('session_expiry_minutes', models.IntegerField(default=2880, help_text='Session expiry time in minutes. After this time, user must login again', verbose_name='Session Expiry (Minutes)')),
                ('max_simultaneous_sessions', models.IntegerField(default=0, help_text='Maximum number of simultaneous active sessions allowed. 0 = unlimited', verbose_name='Max Simultaneous Sessions')),
                ('login_start_time', models.TimeField(default='00:00:00', help_text='Start time for allowed login period (24-hour format, e.g., 08:00:00)', verbose_name='Login Start Time')),
                ('login_end_time', models.TimeField(default='23:59:59', help_text='End time for allowed login period (24-hour format, e.g., 18:00:00)', verbose_name='Login End Time')),
                ('enforce_time_boundary', models.BooleanField(default=False, help_text='If True, users can only login between start and end times', verbose_name='Enforce Time Boundary')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Created By')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Login Setting',
                'verbose_name_plural': 'Login Settings',
                'ordering': ['user_role'],
            },
        ),
        migrations.CreateModel(
            name='OTASettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField()),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ota_settings',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='RegNoLookupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_reg_no', models.CharField(max_length=64)),
                ('imei', models.CharField(max_length=32)),
                ('authorization', models.TextField(blank=True, null=True)),
                ('sessionid', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reg No Lookup Log',
                'verbose_name_plural': 'Reg No Lookup Logs',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(blank=True, help_text='Mobile number for temp user', max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip_name', models.CharField(max_length=255)),
                ('trip_route', models.TextField(help_text='List of lat,long as text')),
                ('tripvehical_tag', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_time_of_travel', models.DurationField()),
                ('distance_travel', models.FloatField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('ended', 'Ended'), ('canceled', 'Canceled')], default='created', max_length=10)),
            ],
        ),
        migrations.RenameIndex(
            model_name='devicemodeltechnicalonboardingdemodevice',
            new_name='skytron_api_onboard_2feb22_idx',
            old_name='skytron_api_onboardi_29cc43_idx',
        ),
        migrations.RenameIndex(
            model_name='devicemodeltechnicalonboardingdemodevice',
            new_name='skytron_api_imei_206930_idx',
            old_name='skytron_api_imei_783d01_idx',
        ),
        migrations.RenameIndex(
            model_name='devicemodeltechnicalonboardingdemodevice',
            new_name='skytron_api_device__1a197e_idx',
            old_name='skytron_api_device__56f5dc_idx',
        ),
        migrations.RenameIndex(
            model_name='devicemodeltechnicalonboardingrequest',
            new_name='skytron_api_manufac_ee775f_idx',
            old_name='skytron_api_manufac_391f94_idx',
        ),
        migrations.RenameIndex(
            model_name='devicemodeltechnicalonboardingrequest',
            new_name='skytron_api_device__0936b2_idx',
            old_name='skytron_api_device__5fcb2d_idx',
        ),
        migrations.RenameIndex(
            model_name='devicemodeltechnicalonboardingrequest',
            new_name='skytron_api_request_091d96_idx',
            old_name='skytron_api_request_601684_idx',
        ),
        migrations.AddField(
            model_name='alertslog',
            name='poi_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skytron_api.pointofinterests'),
        ),
        migrations.AddField(
            model_name='devicestock',
            name='iccid2',
            field=models.CharField(blank=True, max_length=55, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='devicetag',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skytron_api.settings_district'),
        ),
        migrations.AddField(
            model_name='emcall',
            name='em_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pointofinterests',
            name='address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointofinterests',
            name='alert_type',
            field=models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('both', 'Both'), ('none', 'None')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='pointofinterests',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pointofinterests',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pointofinterests',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pointofinterests',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pointofinterests',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pointofinterests',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pointofinterests',
            name='pluscode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pointofinterests',
            name='speed_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pointofinterests',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pointofinterests',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings_vehiclecategory',
            name='working_hour_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings_vehiclecategory',
            name='working_hour_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='User_lat'),
        ),
        migrations.AddField(
            model_name='user',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='User_lon'),
        ),
        migrations.AddField(
            model_name='user',
            name='nf_frequency',
            field=models.IntegerField(default=1, help_text='Number of times per day notifications can be sent (0-1440)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='Notification Frequency Per Day'),
        ),
        migrations.AlterField(
            model_name='alertslog',
            name='type',
            field=models.CharField(choices=[('Route', 'Route'), ('Geofence', 'Geofence'), ('Idling', 'Idling'), ('OfflineDevice', 'OfflineDevice'), ('Overtime', 'Overtime'), ('UnauthorizedStop', 'UnauthorizedStop'), ('UnauthorizedSkip', 'UnauthorizedSkip'), ('NetworkLoss', 'NetworkLoss'), ('GPSLoss', 'GPSLoss'), ('Permit', 'Permit'), ('Permit_3day', 'Permit_3day'), ('Route_overspeed', 'Route_overspeed'), ('state_border_cross', 'state_border_cross'), ('district_border_cross', 'district_border_cross'), ('city_border_cross', 'city_border_cross'), ('Incident', 'Incident'), ('Em', 'Em'), ('EmPublicApp', 'EmPublicApp'), ('EmRegisteredApp', 'EmRegisteredApp'), ('EmMonitorTripSOS', 'EmMonitorTripSOS'), ('EmMonitorTripInvalidPw', 'EmMonitorTripInvalidPw'), ('EmMonitorTripBLEDisconnect', 'EmMonitorTripBLEDisconnect'), ('EmMonitorTripDeviated', 'EmMonitorTripDeviated'), ('Eng', 'Eng'), ('OverSpeed', 'OverSpeed'), ('LowIntBat', 'LowIntBat'), ('LowExtBat', 'LowExtBat'), ('ExtBatDiscnt', 'ExtBatDiscnt'), ('BoxTemp', 'BoxTemp'), ('EmTemp', 'EmTemp'), ('Tilt', 'Tilt'), ('HarshBreak', 'HarshBreak'), ('HarshTurn', 'HarshTurn'), ('HarshAcceleration', 'HarshAccileration')], max_length=50),
        ),
        migrations.AlterField(
            model_name='confirmation',
            name='token',
            field=models.CharField(max_length=1500, unique=True),
        ),
        migrations.AlterField(
            model_name='devicestock',
            name='esim_provider',
            field=models.ManyToManyField(related_name='eSimProvider_devicestock', to='skytron_api.esimprovider'),
        ),
        migrations.AlterField(
            model_name='devicestock',
            name='esim_status',
            field=models.CharField(choices=[('NotAssigned', 'NotAssigned'), ('In_transit_to_dealer', 'In Transit to Dealer'), ('Available_for_fitting', 'Available for Fitting'), ('Fitted', 'Fitted'), ('ESIM_Active_Req_Sent', 'ESIM Active Request Sent'), ('ESIM_Active_Confirmed', 'ESIM Active Confirmed'), ('ESIM_Active_Rejected', 'ESIM_Active_Rejected'), ('IP_PORT_Configured', 'IP Port Configured'), ('SOS_GATEWAY_NO_Configured', 'SOS Gateway No Configured'), ('SMS_GATEWAY_NO_Configured', 'SMS Gateway No Configured'), ('Device_Defective', 'Device Defective'), ('Returned_to_manufacturer', 'Returned to Manufacturer'), ('Device_Untagged', 'Device Untagged')], max_length=55),
        ),
        migrations.AlterField(
            model_name='devicestock',
            name='stock_status',
            field=models.CharField(choices=[('NotAssigned', 'NotAssigned'), ('In_transit_to_dealer', 'In Transit to Dealer'), ('Available_for_fitting', 'Available for Fitting'), ('Fitted', 'Fitted'), ('ESIM_Active_Req_Sent', 'ESIM Active Request Sent'), ('ESIM_Active_Confirmed', 'ESIM Active Confirmed'), ('ESIM_Active_Rejected', 'ESIM_Active_Rejected'), ('IP_PORT_Configured', 'IP Port Configured'), ('SOS_GATEWAY_NO_Configured', 'SOS Gateway No Configured'), ('SMS_GATEWAY_NO_Configured', 'SMS Gateway No Configured'), ('Device_Defective', 'Device Defective'), ('Returned_to_manufacturer', 'Returned to Manufacturer'), ('Device_Untagged', 'Device Untagged')], max_length=55),
        ),
        migrations.AlterField(
            model_name='devicetag',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.settings_vehiclecategory'),
        ),
        migrations.AlterField(
            model_name='emcall',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('desk_ex_assigned', 'desk_ex_assigned'), ('broadcast_pending', 'broadcast_pending'), ('field_ex_aproaching', 'field_ex_aproaching'), ('field_ex_arrived', 'field_ex_arrived'), ('closed_false_alert', 'closed_false_alert'), ('closed', 'closed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='emcallassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('arriving', 'arriving'), ('arrived', 'arrived'), ('closed_false_alert', 'closed_false_alert'), ('closed', 'closed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='esimprovider',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('UserVerified', 'UserVerified'), ('StateAdminVerified', 'StateAdminVerified'), ('UserExpired', 'UserExpired'), ('Discontinued', 'Discontinued'), ('Reject', 'Reject'), ('Allow to login', 'Allow to login'), ('Allow to add dealer', 'Allow to add dealer'), ('Accept', 'Accept')], max_length=20),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('UserVerified', 'UserVerified'), ('StateAdminVerified', 'StateAdminVerified'), ('UserExpired', 'UserExpired'), ('Discontinued', 'Discontinued'), ('Reject', 'Reject'), ('Allow to login', 'Allow to login'), ('Allow to add dealer', 'Allow to add dealer'), ('Accept', 'Accept')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pointofinterests',
            name='use_type',
            field=models.CharField(choices=[('StateBoundary', 'StateBoundary'), ('DistrictBoundary', 'DistrictBoundary'), ('CityBoundary', 'CityBoundary'), ('VillageBoundary', 'VillageBoundary'), ('PermitRoute', 'PermitRoute'), ('Police', 'Police'), ('School', 'School'), ('Hospital', 'Hospital'), ('PoliceStation', 'PoliceStation'), ('BusStop', 'BusStop'), ('NoParking', 'NoParking'), ('RailwayStation', 'RailwayStation'), ('Airport', 'Airport'), ('FuelStation', 'FuelStation'), ('TollGate', 'TollGate'), ('Other', 'Other'), ('Personal', 'Personal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tokenblacklist',
            name='token',
            field=models.CharField(db_index=True, max_length=1500, unique=True, verbose_name='Token'),
        ),
        migrations.AddIndex(
            model_name='gpsdata',
            index=models.Index(fields=['device_tag', '-entry_time', '-id'], name='gpsdata_tag_time_id_idx'),
        ),
        migrations.AddField(
            model_name='trip',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regnolookuplog',
            name='device_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regno_lookup_logs', to='skytron_api.devicetag'),
        ),
        migrations.AddField(
            model_name='otasettings',
            name='triggered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ota_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentregister',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentregister',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='busstand',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_stands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='regnolookuplog',
            index=models.Index(fields=['vehicle_reg_no'], name='skytron_api_vehicle_1c694a_idx'),
        ),
        migrations.AddIndex(
            model_name='regnolookuplog',
            index=models.Index(fields=['imei'], name='skytron_api_imei_ed0138_idx'),
        ),
        migrations.AddIndex(
            model_name='regnolookuplog',
            index=models.Index(fields=['created_at'], name='skytron_api_created_fa6088_idx'),
        ),
    ]
