# Generated by Django 4.1.13 on 2024-07-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0021_devicemodel_otp_time_alter_captcha_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='79fc660a54d3423b9e462d55d720ab12', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='settings_vehiclecategory',
            name='category',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
