# Generated by Django 4.2.9 on 2024-06-23 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0021_captcha_delete_mathcaptcha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='59f68619f001486eb56f353774dea275', max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='EmergencyCall_assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_time', models.DateTimeField()),
                ('accept_time', models.DateTimeField(blank=True, null=True)),
                ('complete_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('EmergencyCall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.emergencycall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
