# Generated by Django 4.1.13 on 2024-07-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0022_alter_captcha_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dto_rto',
            name='file_authorisation_letter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='c332460f29344dac9930150419a4116c', max_length=32, unique=True),
        ),
    ]
