# Generated by Django 4.2.17 on 2026-04-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0022_blekey_busstand_incidentregister_loginsettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterests',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
