# Generated by Django 4.2.9 on 2024-06-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0022_alter_captcha_key_emergencycall_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='b955272b370244288ae95d8bb9ea4741', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
