# Generated by Django 4.1.13 on 2024-07-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0023_dto_rto_file_authorisation_letter_alter_captcha_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='69716a2fff98459786e5f844178bcc84', max_length=32, unique=True),
        ),
    ]
