# Generated by Django 4.2.9 on 2024-06-26 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0023_user_last_activity_user_login_alter_captcha_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencycall_assignment',
            old_name='EmergencyCall_id',
            new_name='emergencyCall_id',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='esim_provider',
            field=models.ManyToManyField(blank=True, related_name='eSimProvider_Manufacturer', to='skytron_api.esimprovider'),
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='4d641d657f324bae854cc5669a37ca22', max_length=32, unique=True),
        ),
        migrations.RemoveField(
            model_name='devicestock',
            name='esim_provider',
        ),
        migrations.AlterField(
            model_name='emergencycall',
            name='desk_executive_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desk_executive_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emergencycall',
            name='field_executive_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_executive_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicestock',
            name='esim_provider',
            field=models.ManyToManyField(blank=True, related_name='eSimProvider_devicestock', to='skytron_api.esimprovider'),
        ),
    ]
