# Generated by Django 4.2.17 on 2026-04-05 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0023_pointofinterests_address_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emcallassignment',
            name='ex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exec_id', to='skytron_api.em_ex'),
        ),
    ]
