# Generated by Django 4.2.17 on 2026-04-07 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0024_emcallassignment_ex_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Order of this stop in the route')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolBusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roll_number', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='skytron_api.school')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('stateadmin', 'State Admin'), ('devicemanufacture', 'Device Manufacture'), ('dealer', 'Dealer'), ('owner', 'Owner'), ('esimprovider', 'eSimProvider'), ('filment', 'Filment'), ('sosadmin', 'SOS Admin'), ('teamleader', 'Team Leader'), ('sosexecutive', 'SOS Executive'), ('schooladmin', 'School Admin'), ('parentuser', 'Parent User')], max_length=20, verbose_name='Role'),
        ),
        migrations.CreateModel(
            name='SchoolRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('route_points', models.JSONField(blank=True, default=list, help_text='List of lat/lng coordinates defining the route path')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_routes', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='skytron_api.school')),
                ('stops', models.ManyToManyField(blank=True, related_name='routes', through='skytron_api.RouteStop', to='skytron_api.schoolbusstop')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('national', 'National'), ('festival', 'Festival'), ('local', 'Local'), ('emergency', 'Emergency')], default='festival', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_holidays', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='skytron_api.school')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_holidays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SchoolBusTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('COMPLETED', 'Completed'), ('UNSCHEDULED', 'Unscheduled')], default='PLANNED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skytron_api.devicetag')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skytron_api.schoolroute')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='skytron_api.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolBusTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('tagged_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_tags', to='skytron_api.devicetag')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_tags', to='skytron_api.school')),
            ],
        ),
        migrations.AddField(
            model_name='schoolbusstop',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bus_stops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolbusstop',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_stops', to='skytron_api.school'),
        ),
        migrations.CreateModel(
            name='SchoolBusDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('RC', 'Vehicle RC'), ('PERMIT', 'School Bus Permit'), ('AUTH_LETTER', 'Authorization Letter'), ('VLTD_RECEIPT', 'VLTD Fitment Receipt')], max_length=30)),
                ('file_path', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='skytron_api.devicetag')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_documents', to='skytron_api.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('otp', models.CharField(blank=True, max_length=128)),
                ('otp_verified', models.BooleanField(default=False)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='admin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_schools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routestop',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='skytron_api.schoolroute'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stops', to='skytron_api.schoolbusstop'),
        ),
        migrations.CreateModel(
            name='RouteBusAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_assignments', to='skytron_api.devicetag')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_assignments', to='skytron_api.schoolroute')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_bus_assignments', to='skytron_api.school')),
            ],
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='skytron_api.school')),
                ('students', models.ManyToManyField(blank=True, related_name='parents', to='skytron_api.student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('overspeed', 'Overspeed'), ('harsh_braking', 'Harsh Braking'), ('harsh_acceleration', 'Harsh Acceleration'), ('route_deviation', 'Route Deviation'), ('sos', 'SOS')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.devicetag')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.school')),
            ],
        ),
        migrations.CreateModel(
            name='StudentBusAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_allocations', to='skytron_api.devicetag')),
                ('drop_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drop_students', to='skytron_api.schoolbusstop')),
                ('pickup_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_students', to='skytron_api.schoolbusstop')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_allocations', to='skytron_api.schoolroute')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_allocations', to='skytron_api.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'is_active'], name='skytron_api_student_4bc02b_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_status', models.BooleanField(default=False)),
                ('drop_status', models.BooleanField(default=False)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('drop_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_present', models.BooleanField(default=False)),
                ('drop_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drop_attendances', to='skytron_api.schoolbusstop')),
                ('pickup_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_attendances', to='skytron_api.schoolbusstop')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='skytron_api.student')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='skytron_api.schoolbustrip')),
            ],
            options={
                'indexes': [models.Index(fields=['trip'], name='skytron_api_trip_id_cbf1d1_idx'), models.Index(fields=['student'], name='skytron_api_student_f75345_idx')],
                'unique_together': {('trip', 'student')},
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'class_name'], name='skytron_api_school__c17202_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('school', 'class_name', 'roll_number'), name='unique_roll_per_class_per_school'),
        ),
        migrations.AddIndex(
            model_name='schoolroute',
            index=models.Index(fields=['school', 'status'], name='skytron_api_school__ca418d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolroute',
            unique_together={('school', 'name')},
        ),
        migrations.AddIndex(
            model_name='schoolholiday',
            index=models.Index(fields=['school', 'date'], name='skytron_api_school__d944d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolholiday',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('school', 'date'), name='unique_active_holiday_per_school_date'),
        ),
        migrations.AddIndex(
            model_name='schoolbustrip',
            index=models.Index(fields=['school', 'trip_date'], name='skytron_api_school__6a6b30_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolbustag',
            index=models.Index(fields=['school', 'is_active'], name='skytron_api_school__3fef03_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolbustag',
            unique_together={('school', 'bus')},
        ),
        migrations.AddIndex(
            model_name='schoolbusstop',
            index=models.Index(fields=['school', 'is_active'], name='skytron_api_school__a3c05c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolbusstop',
            unique_together={('school', 'name')},
        ),
        migrations.AddIndex(
            model_name='schoolbusdocument',
            index=models.Index(fields=['school', 'bus'], name='skytron_api_school__d2c3cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolbusdocument',
            unique_together={('bus', 'document_type')},
        ),
        migrations.AddIndex(
            model_name='schoolapplication',
            index=models.Index(fields=['status'], name='skytron_api_status_d3f09b_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolapplication',
            constraint=models.UniqueConstraint(fields=('latitude', 'longitude'), name='unique_school_location'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['is_active'], name='skytron_api_is_acti_5009ed_idx'),
        ),
        migrations.AddIndex(
            model_name='routestop',
            index=models.Index(fields=['route', 'order'], name='skytron_api_route_i_c351b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('route', 'stop')},
        ),
        migrations.AddIndex(
            model_name='routebusassignment',
            index=models.Index(fields=['school', 'route', 'is_active'], name='skytron_api_school__104d86_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routebusassignment',
            unique_together={('school', 'bus')},
        ),
        migrations.AddIndex(
            model_name='parentprofile',
            index=models.Index(fields=['school'], name='skytron_api_school__03b1ba_idx'),
        ),
        migrations.AddIndex(
            model_name='parentprofile',
            index=models.Index(fields=['is_active'], name='skytron_api_is_acti_ed5dbc_idx'),
        ),
        migrations.AddIndex(
            model_name='busalert',
            index=models.Index(fields=['school', 'alert_type'], name='skytron_api_school__40e7e1_idx'),
        ),
    ]
