# Generated by Django 4.2.9 on 2024-06-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0024_rename_emergencycall_id_emergencycall_assignment_emergencycall_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='0b5b42adebb34bbfa94786ad20971f2a', max_length=32, unique=True),
        ),
    ]
