# Generated by Django 4.1.13 on 2024-07-31 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0024_alter_captcha_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetag',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='devicetag',
            name='otp_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='523e999fb1e6462aaddcf5ad1677d185', max_length=32, unique=True),
        ),
    ]
