# Generated by Django 4.2.9 on 2024-06-26 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0025_alter_captcha_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='b164bc25a8ce4361ae4b27b0058878d7', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='emergencycall',
            name='desk_executive_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desk_executive_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emergencycall',
            name='field_executive_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_executive_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
