# Generated by Django 4.1.13 on 2024-07-31 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0025_devicetag_otp_devicetag_otp_time_alter_captcha_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecop',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='devicecop',
            name='otp_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='5fa1f0d78a8e4fe8b0b5d3e2d126619e', max_length=32, unique=True),
        ),
    ]
