# Generated by Django 4.2.17 on 2026-04-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0025_routestop_school_schoolbusstop_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='em_contact',
            field=models.CharField(max_length=25, verbose_name='em_contact'),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='mobile',
            field=models.CharField(max_length=25, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='mobile_no',
            field=models.CharField(blank=True, help_text='Mobile number for temp user', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=25, unique=True, verbose_name='Mobile'),
        ),
    ]
