# Generated by Django 4.2.9 on 2024-06-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0026_alter_captcha_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='b3305acec7794ab9b8c1c29194e6c420', max_length=32, unique=True),
        ),
    ]
