# Generated by Django 4.2.17 on 2026-04-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0026_alter_tempuser_em_contact_alter_tempuser_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('UserVerified', 'UserVerified'), ('StateAdminVerified', 'StateAdminVerified'), ('UserExpired', 'UserExpired'), ('Discontinued', 'Discontinued'), ('Reject', 'Reject'), ('Allow to login', 'Allow to login'), ('Allow to add dealer', 'Allow to add dealer'), ('Accept', 'Accept'), ('TechnicalOnboardingApproved', 'Technical Onboarding Approved'), ('TechnicalOnboardingRejected', 'Technical Onboarding Rejected')], max_length=30),
        ),
    ]
