# Generated by Django 4.1.13 on 2024-07-31 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0026_devicecop_otp_devicecop_otp_time_alter_captcha_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='69546c6c582d42b588fe06b170c2cbfc', max_length=32, unique=True),
        ),
    ]
