# Generated by Django 4.2.9 on 2024-06-26 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0027_alter_captcha_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='2263aa6790de4b288e12f997f9cba0ec', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='help',
            name='field_ex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='help_field_executive_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
