# Generated by Django 4.2.17 on 2026-04-08 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0027_alter_manufacturer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=255, verbose_name='Test Agency Name')),
                ('company_address', models.CharField(blank=True, max_length=255, null=True)),
                ('company_pin', models.CharField(blank=True, max_length=20, null=True)),
                ('file_authLetter', models.CharField(blank=True, max_length=255, null=True)),
                ('idProofno', models.CharField(blank=True, max_length=255, null=True)),
                ('file_idProof', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('expirydate', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('UserVerified', 'UserVerified'), ('UserExpired', 'UserExpired'), ('Discontinued', 'Discontinued'), ('Accept', 'Accept'), ('Reject', 'Reject')], max_length=20)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testagency_createdby', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='testagency_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
