# Generated by Django 4.1.13 on 2024-07-31 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0027_alter_captcha_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skytron_api.manufacturer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='3eb82c5dbfad446f95f565b7e9d886a5', max_length=32, unique=True),
        ),
    ]
