# Generated by Django 4.1.13 on 2024-07-31 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0028_retailer_manufacturer_alter_captcha_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestock',
            name='assigned',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicestock',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicestock',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skytron_api.retailer'),
        ),
        migrations.AddField(
            model_name='devicestock',
            name='shipping_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicestock',
            name='stock_status',
            field=models.CharField(choices=[('NotAssigned', 'NotAssigned'), ('In_transit_to_dealer', 'In Transit to Dealer'), ('Available_for_fitting', 'Available for Fitting'), ('Fitted', 'Fitted'), ('ESIM_Active_Req_Sent', 'ESIM Active Request Sent'), ('ESIM_Active_Confirmed', 'ESIM Active Confirmed'), ('IP_PORT_Configured', 'IP Port Configured'), ('SOS_GATEWAY_NO_Configured', 'SOS Gateway No Configured'), ('SMS_GATEWAY_NO_Configured', 'SMS Gateway No Configured'), ('Device_Defective', 'Device Defective'), ('Returned_to_manufacturer', 'Returned to Manufacturer')], default='NotAssigned', max_length=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='2c09e0b014f442e9b2c5b43da2898892', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='devicestock',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createby_USERdevicestock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='StockAssignment',
        ),
    ]
