# Generated by Django 4.2.9 on 2024-07-06 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0028_alter_captcha_key_alter_help_field_ex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sos_admin',
            name='district',
        ),
        migrations.AddField(
            model_name='retailer',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skytron_api.settings_district'),
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='d36cbcc57da541a7a236543f37809478', max_length=32, unique=True),
        ),
    ]
