# Generated by Django 4.2.17 on 2026-04-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0028_testagency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetag',
            name='status',
            field=models.CharField(choices=[('Dealer_OTP_Sent', 'Dealer OTP Sent'), ('Dealer_OTP_Verified', 'Dealer_OTP_Verified'), ('TempActive', 'TempActive'), ('Owner_OTP_Sent', 'Owner OTP Sent'), ('Owner_OTP_Verified', 'Owner OTP Verified'), ('RegNo_Configuration_SentToDevice', 'Reg No Configuration Sent to Device'), ('RegNo_Configuration_Confirmed', 'Reg No Configuration Confirmed'), ('Live_Location_Confirmed', 'Live Location Confirmed'), ('SOS_Confirmed', 'SOS Confirmed'), ('Device_Active', 'Device Active'), ('Device_Not_Active', 'Device Not Active'), ('Device_Untagged', 'Device Untagged'), ('Device_Untagged', 'Device Untagged'), ('Owner_Final_OTP_Verified', 'Owner Final OTP Verified'), ('TagDeleted', 'TagDeleted'), ('untaged_after_failed_taging', 'Untagged After Failed Tagging')], max_length=255),
        ),
    ]
