# Generated by Django 4.1.13 on 2024-07-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0029_remove_sos_admin_district_retailer_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='564f4020f3024130acb539bf7297a54e', max_length=32, unique=True),
        ),
    ]
