# Generated by Django 4.1.13 on 2024-07-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0029_devicestock_assigned_devicestock_assigned_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='abf7341d6cf24cc8a77989e1b1f49949', max_length=32, unique=True),
        ),
    ]
