# Generated by Django 4.1.13 on 2024-07-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0030_alter_captcha_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='0b6201d6d62547c58bf335d235bb2b39', max_length=32, unique=True),
        ),
    ]
