# Generated by Django 4.1.13 on 2024-08-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0030_alter_captcha_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='c1bb7c0219424ca1834c740271cda497', max_length=32, unique=True),
        ),
    ]
