# Generated by Django 4.2.17 on 2026-04-13 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0030_testagencydetails'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolbustag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='routebusassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolbusstop',
            name='timing',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolbustag',
            name='otp',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='schoolbustag',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schoolbustag',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolbustag',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolbustag',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolbustag',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolbustag',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_bus_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolbustag',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolbustag',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_bus_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolbustag',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolroute',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolbusdocument',
            name='document_type',
            field=models.CharField(choices=[('RC', 'Vehicle RC'), ('PERMIT', 'School Bus Permit'), ('AUTH_LETTER', 'Authorization Letter'), ('VLTD_RECEIPT', 'VLTD Fitment Receipt'), ('REQUEST_LETTER', 'Request Letter From School Principal')], max_length=30),
        ),
        migrations.AlterField(
            model_name='schoolroute',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='schoolbustag',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'approved'])), fields=('school', 'bus'), name='unique_active_tag_per_school_bus'),
        ),
    ]
