# Generated by Django 4.1.13 on 2024-08-01 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0031_alter_captcha_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='2d41d8f574774630bc0bb82ed862274b', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='devicetag',
            name='vehicle_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skytron_api.vehicleowner'),
        ),
    ]
