# Generated by Django 4.2.17 on 2026-04-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0031_alter_schoolbustag_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='mqtt_pw',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
