# Generated by Django 4.1.13 on 2024-07-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0031_alter_captcha_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='10c942fed47443ce87bc17930dda5b88', max_length=32, unique=True),
        ),
    ]
