# Generated by Django 4.2.17 on 2026-04-20 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0032_devicemodel_mqtt_pw'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='school',
            name='skytron_api_is_acti_5009ed_idx',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='address',
            new_name='school_address',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='contact_email',
            new_name='school_email',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='latitude',
            new_name='school_lat',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='longitude',
            new_name='school_lon',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='name',
            new_name='school_name',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='contact_phone',
            new_name='school_phone',
        ),
        migrations.RemoveField(
            model_name='school',
            name='admin_user',
        ),
        migrations.AddField(
            model_name='school',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skytron_api.settings_district'),
        ),
        migrations.AddField(
            model_name='school',
            name='extra_documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='school',
            name='file_authorization_letter',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='file_id_proof',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_pin',
            field=models.CharField(db_index=True, default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skytron_api.settings_state'),
        ),
        migrations.AddField(
            model_name='school',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SETUP_SENT', 'Setup Sent'), ('SETUP_LINK_APPROVED', 'Setup Link Approved')], db_index=True, default='SUBMITTED', max_length=25),
        ),
        migrations.AddField(
            model_name='school',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='school',
            name='users',
            field=models.ManyToManyField(related_name='schooladmin_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['status', 'is_active'], name='skytron_api_status_69f4bf_idx'),
        ),
    ]
