# Generated by Django 4.1.13 on 2024-08-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0032_alter_captcha_key_alter_devicetag_vehicle_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='5f69e614b66e4b1eae77bc92953122df', max_length=32, unique=True),
        ),
    ]
