# Generated by Django 4.1.13 on 2024-07-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0032_alter_captcha_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='71016001911248c5b9aa03603268e657', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Access',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Access'),
        ),
    ]
