# Generated by Django 4.1.13 on 2024-08-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0033_alter_captcha_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='70fa599c985f48a8aed5655c2f9f87ff', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='devicetag',
            name='status',
            field=models.CharField(choices=[('Dealer_OTP_Sent', 'Dealer OTP Sent'), ('Dealer_OTP_Verified Esim activation req sent', 'Dealer_OTP_Verified Esim activation req sent'), ('TempActive', 'TempActive'), ('Owner_OTP_Sent', 'Owner OTP Sent'), ('Owner_OTP_Verified', 'Owner OTP Verified'), ('RegNo_Configuration_SentToDevice', 'Reg No Configuration Sent to Device'), ('RegNo_Configuration_Confirmed', 'Reg No Configuration Confirmed'), ('Live_Location_Confirmed', 'Live Location Confirmed'), ('SOS_Confirmed', 'SOS Confirmed'), ('Device_Active', 'Device Active'), ('Device_Not_Active', 'Device Not Active'), ('Device_Untagged', 'Device Untagged')], max_length=255),
        ),
    ]
