# Generated by Django 4.2.17 on 2026-04-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0033_remove_school_skytron_api_is_acti_5009ed_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='assam_office_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='assam_office_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='assam_office_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='assam_office_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='assam_office_pin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='devicemodeltechnicalonboardingrequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('ongoing_evaluation', 'Ongoing Evaluation'), ('technically_compatible', 'Technically Compatible'), ('technically_not_compatible', 'Technically Not Compatible'), ('StateAdminApproved', 'State Admin Approved'), ('StateAdminRejected', 'State Admin Rejected')], db_index=True, default='submitted', max_length=30),
        ),
    ]
