# Generated by Django 4.2.17 on 2026-04-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0034_manufacturer_assam_office_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestock',
            name='esim_validity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
