# Generated by Django 4.1.13 on 2024-08-02 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0035_alter_captcha_key_alter_devicetag_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='4bacb00c1bab44b290fc175593db68ee', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='devicetag',
            name='tagged_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
