# Generated by Django 4.2.17 on 2026-04-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0035_alter_devicestock_esim_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleowner',
            name='file_GSTCertificate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicleowner',
            name='gstno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
