# Generated by Django 4.2.17 on 2026-04-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0036_vehicleowner_file_gstcertificate_vehicleowner_gstno'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetag',
            name='device_sell_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
