# Generated by Django 4.1.13 on 2024-08-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0036_alter_captcha_key_alter_devicetag_tagged_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='ef32e53b3a744ff9b7c0a09eed1a7fff', max_length=32, unique=True),
        ),
    ]
