# Generated by Django 4.2.17 on 2026-04-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0037_devicetag_device_sell_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetag',
            name='sale_type',
            field=models.CharField(choices=[('withinstate', 'Within State'), ('interstate', 'Inter State')], default='withinstate', max_length=20),
        ),
    ]
