# Generated by Django 4.1.13 on 2024-08-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0037_alter_captcha_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateadmin',
            name='file_authorisation_letter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='0f409d75ac274a2dac0b58c6b7134729', max_length=32, unique=True),
        ),
    ]
