# Generated by Django 4.1.13 on 2024-08-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0038_stateadmin_file_authorisation_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='0cae9ba4c56d43e0be4f000172598e02', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='devicestock',
            name='stock_status',
            field=models.CharField(choices=[('NotAssigned', 'NotAssigned'), ('In_transit_to_dealer', 'In Transit to Dealer'), ('Available_for_fitting', 'Available for Fitting'), ('Fitted', 'Fitted'), ('ESIM_Active_Req_Sent', 'ESIM Active Request Sent'), ('ESIM_Active_Confirmed', 'ESIM Active Confirmed'), ('ESIM_Active_Rejected', 'ESIM_Active_Rejected'), ('IP_PORT_Configured', 'IP Port Configured'), ('SOS_GATEWAY_NO_Configured', 'SOS Gateway No Configured'), ('SMS_GATEWAY_NO_Configured', 'SMS Gateway No Configured'), ('Device_Defective', 'Device Defective'), ('Returned_to_manufacturer', 'Returned to Manufacturer')], max_length=55),
        ),
    ]
