# Generated by Django 4.1.13 on 2024-08-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0039_alter_captcha_key_alter_devicestock_stock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='1b2e4fcf36084df5900bd1e14397023b', max_length=32, unique=True),
        ),
    ]
