# Generated by Django 4.1.13 on 2024-08-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0041_devicestock_esim_status_alter_captcha_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=45)),
                ('system_info', models.TextField()),
                ('request_url', models.URLField()),
                ('request_type', models.CharField(max_length=10)),
                ('headers', models.TextField()),
                ('incoming_data', models.TextField()),
                ('response_type', models.CharField(max_length=10)),
                ('error_code', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='14c833b704364c3c84964c80b014279d', max_length=32, unique=True),
        ),
    ]
