# Generated by Django 4.2.17 on 2026-06-06 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0042_add_prohibited_area_unauthorized_parking_alert_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Express', 'Express'), ('Ordinary', 'Ordinary'), ('AC', 'AC'), ('City_Bus', 'City Bus'), ('Sleeper', 'Sleeper'), ('Deluxe', 'Deluxe')], max_length=50)),
                ('start_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('canceled', 'Canceled'), ('started', 'Started'), ('completed', 'Completed')], default='created', max_length=20)),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_schedules', to='skytron_api.devicetag')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_schedules_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PermitCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_name', models.CharField(max_length=255)),
                ('violation_type', models.CharField(choices=[('Route', 'Route'), ('Geofence', 'Geofence'), ('Idling', 'Idling'), ('OfflineDevice', 'OfflineDevice'), ('Overtime', 'Overtime'), ('UnauthorizedStop', 'UnauthorizedStop'), ('UnauthorizedSkip', 'UnauthorizedSkip'), ('NetworkLoss', 'NetworkLoss'), ('GPSLoss', 'GPSLoss'), ('Permit', 'Permit'), ('Permit_3day', 'Permit_3day'), ('Route_overspeed', 'Route_overspeed'), ('state_border_cross', 'state_border_cross'), ('district_border_cross', 'district_border_cross'), ('city_border_cross', 'city_border_cross'), ('Incident', 'Incident'), ('Em', 'Em'), ('EmPublicApp', 'EmPublicApp'), ('EmRegisteredApp', 'EmRegisteredApp'), ('EmMonitorTripSOS', 'EmMonitorTripSOS'), ('EmMonitorTripInvalidPw', 'EmMonitorTripInvalidPw'), ('EmMonitorTripBLEDisconnect', 'EmMonitorTripBLEDisconnect'), ('EmMonitorTripDeviated', 'EmMonitorTripDeviated'), ('Eng', 'Eng'), ('OverSpeed', 'OverSpeed'), ('LowIntBat', 'LowIntBat'), ('LowExtBat', 'LowExtBat'), ('ExtBatDiscnt', 'ExtBatDiscnt'), ('BoxTemp', 'BoxTemp'), ('EmTemp', 'EmTemp'), ('Tilt', 'Tilt'), ('HarshBreak', 'HarshBreak'), ('HarshTurn', 'HarshTurn'), ('HarshAcceleration', 'HarshAcceleration'), ('UnauthorizedParking', 'UnauthorizedParking'), ('Prohibited_Area', 'Prohibited_Area')], max_length=250)),
                ('rule_details', models.TextField(help_text='Rule details as per Motor Vehicle Act')),
                ('penalty', models.CharField(help_text='Penalty details as per Motor Vehicle Act', max_length=250)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('challan_code', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('active', 'Active'), ('deactive', 'Deactive')], default='created', max_length=20)),
                ('activation_datetime', models.DateTimeField(blank=True, null=True)),
                ('deactivation_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permit_conditions_created', to=settings.AUTH_USER_MODEL)),
                ('vehicle_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permit_conditions', to='skytron_api.settings_vehiclecategory')),
            ],
        ),
        migrations.CreateModel(
            name='PublicBusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('route_number', models.CharField(max_length=50, unique=True)),
                ('route_path', models.JSONField(blank=True, default=list, help_text='List of lat/lng coordinates defining the route path')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], default='active', max_length=20)),
                ('last_activation_date', models.DateTimeField(blank=True, null=True)),
                ('last_deactivation_date', models.DateTimeField(blank=True, null=True)),
                ('deactivation_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_bus_routes_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PublicBusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], default='active', max_length=20)),
                ('last_activation_date', models.DateTimeField(blank=True, null=True)),
                ('last_deactivation_date', models.DateTimeField(blank=True, null=True)),
                ('deactivation_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_bus_stops_created', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_bus_stops', to='skytron_api.settings_district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_bus_stops', to='skytron_api.settings_state')),
            ],
        ),
        migrations.AddField(
            model_name='requestlog',
            name='response_time_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alertslog',
            name='type',
            field=models.CharField(choices=[('Route', 'Route'), ('Geofence', 'Geofence'), ('Idling', 'Idling'), ('OfflineDevice', 'OfflineDevice'), ('Overtime', 'Overtime'), ('UnauthorizedStop', 'UnauthorizedStop'), ('UnauthorizedSkip', 'UnauthorizedSkip'), ('NetworkLoss', 'NetworkLoss'), ('GPSLoss', 'GPSLoss'), ('Permit', 'Permit'), ('Permit_3day', 'Permit_3day'), ('Route_overspeed', 'Route_overspeed'), ('state_border_cross', 'state_border_cross'), ('district_border_cross', 'district_border_cross'), ('city_border_cross', 'city_border_cross'), ('Incident', 'Incident'), ('Em', 'Em'), ('EmPublicApp', 'EmPublicApp'), ('EmRegisteredApp', 'EmRegisteredApp'), ('EmMonitorTripSOS', 'EmMonitorTripSOS'), ('EmMonitorTripInvalidPw', 'EmMonitorTripInvalidPw'), ('EmMonitorTripBLEDisconnect', 'EmMonitorTripBLEDisconnect'), ('EmMonitorTripDeviated', 'EmMonitorTripDeviated'), ('Eng', 'Eng'), ('OverSpeed', 'OverSpeed'), ('LowIntBat', 'LowIntBat'), ('LowExtBat', 'LowExtBat'), ('ExtBatDiscnt', 'ExtBatDiscnt'), ('BoxTemp', 'BoxTemp'), ('EmTemp', 'EmTemp'), ('Tilt', 'Tilt'), ('HarshBreak', 'HarshBreak'), ('HarshTurn', 'HarshTurn'), ('HarshAcceleration', 'HarshAcceleration'), ('UnauthorizedParking', 'UnauthorizedParking'), ('Prohibited_Area', 'Prohibited_Area')], max_length=50),
        ),
        migrations.CreateModel(
            name='PublicRouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('arrival_time_min', models.PositiveIntegerField(default=0, help_text='Minutes from route start time to arrive at this stop')),
                ('halt_time_min', models.PositiveIntegerField(default=0, help_text='Minutes bus halts at this stop')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='skytron_api.publicbusroute')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stops', to='skytron_api.publicbusstop')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='publicbusroute',
            name='destination_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_as_destination', to='skytron_api.publicbusstop'),
        ),
        migrations.AddField(
            model_name='publicbusroute',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_bus_routes', to='skytron_api.settings_district'),
        ),
        migrations.AddField(
            model_name='publicbusroute',
            name='source_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_as_source', to='skytron_api.publicbusstop'),
        ),
        migrations.AddField(
            model_name='publicbusroute',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_bus_routes', to='skytron_api.settings_state'),
        ),
        migrations.AddField(
            model_name='publicbusroute',
            name='stops',
            field=models.ManyToManyField(blank=True, related_name='routes', through='skytron_api.PublicRouteStop', to='skytron_api.publicbusstop'),
        ),
        migrations.CreateModel(
            name='BusScheduleStopETA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('scheduled_arrival', models.DateTimeField()),
                ('scheduled_departure', models.DateTimeField()),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('route_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stop_etas', to='skytron_api.publicroutestop')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_etas', to='skytron_api.busschedule')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='busschedule',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='skytron_api.publicbusroute'),
        ),
        migrations.CreateModel(
            name='ViolationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('violation_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert_log', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violations', to='skytron_api.alertslog')),
                ('device_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violations', to='skytron_api.devicetag')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skytron_api.settings_district')),
                ('permit_condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violations', to='skytron_api.permitcondition')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skytron_api.settings_state')),
            ],
            options={
                'indexes': [models.Index(fields=['device_tag'], name='skytron_api_device__8649a0_idx'), models.Index(fields=['violation_datetime'], name='skytron_api_violati_45164a_idx'), models.Index(fields=['permit_condition'], name='skytron_api_permit__575f76_idx'), models.Index(fields=['state'], name='skytron_api_state_i_246a94_idx'), models.Index(fields=['district'], name='skytron_api_distric_20e8a2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='publicroutestop',
            index=models.Index(fields=['route', 'order', 'stop'], name='skytron_api_route_i_555d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='publicbusstop',
            index=models.Index(fields=['state', 'status'], name='skytron_api_state_i_76f470_idx'),
        ),
        migrations.AddIndex(
            model_name='publicbusstop',
            index=models.Index(fields=['district', 'status'], name='skytron_api_distric_858c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='publicbusstop',
            index=models.Index(fields=['latitude', 'longitude'], name='skytron_api_latitud_246ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='publicbusroute',
            index=models.Index(fields=['state', 'status'], name='skytron_api_state_i_8ce14e_idx'),
        ),
        migrations.AddIndex(
            model_name='publicbusroute',
            index=models.Index(fields=['route_number'], name='skytron_api_route_n_d47ce6_idx'),
        ),
        migrations.AddIndex(
            model_name='permitcondition',
            index=models.Index(fields=['status'], name='skytron_api_status_0454d4_idx'),
        ),
        migrations.AddIndex(
            model_name='permitcondition',
            index=models.Index(fields=['violation_type'], name='skytron_api_violati_10512f_idx'),
        ),
        migrations.AddIndex(
            model_name='permitcondition',
            index=models.Index(fields=['vehicle_category'], name='skytron_api_vehicle_88d154_idx'),
        ),
        migrations.AddIndex(
            model_name='permitcondition',
            index=models.Index(fields=['activation_datetime', 'deactivation_datetime'], name='skytron_api_activat_cbf06f_idx'),
        ),
        migrations.AddIndex(
            model_name='busschedulestopeta',
            index=models.Index(fields=['schedule', 'order'], name='skytron_api_schedul_5f7fd2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='busschedulestopeta',
            unique_together={('schedule', 'route_stop')},
        ),
        migrations.AddIndex(
            model_name='busschedule',
            index=models.Index(fields=['route', 'start_datetime'], name='skytron_api_route_i_99f50f_idx'),
        ),
        migrations.AddIndex(
            model_name='busschedule',
            index=models.Index(fields=['bus', 'start_datetime'], name='skytron_api_bus_id_4b89dc_idx'),
        ),
        migrations.AddIndex(
            model_name='busschedule',
            index=models.Index(fields=['status'], name='skytron_api_status_33702e_idx'),
        ),
    ]
