# Generated by Django 4.1.13 on 2024-08-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0042_requestlog_alter_captcha_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='2f72a63dcfd64cbf998927f1d5454030', max_length=32, unique=True),
        ),
    ]
