# Generated by Django 4.1.13 on 2024-08-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0043_alter_captcha_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='6d635a95b1f347a6a4c17d56bacb1d2e', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='ip_address',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='request_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='response_type',
            field=models.CharField(max_length=100),
        ),
    ]
