# Generated by Django 4.2.17 on 2026-06-08 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0043_busschedule_permitcondition_publicbusroute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_builtin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_role_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role Type',
                'verbose_name_plural': 'User Role Types',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('gps_tracking', 'GPS Live Tracking'), ('gps_history', 'GPS History'), ('gps_clustering', 'GPS Cluster / Grid'), ('device_management', 'Device Model Management'), ('device_stock', 'Device Stock & Inventory'), ('vehicle_tagging', 'Vehicle Tagging'), ('driver_management', 'Driver Management'), ('owner_management', 'Vehicle Owner Management'), ('manufacturer_management', 'Manufacturer Management'), ('dealer_management', 'Dealer Management'), ('stateadmin_management', 'State Admin Management'), ('esim_management', 'eSIM Provider Management'), ('emergency_management', 'Emergency (SOS) Management'), ('emergency_teams', 'Emergency Teams'), ('poi_management', 'Points of Interest'), ('route_management', 'Route Management'), ('alerts', 'Alerts & Notifications'), ('reports', 'Reports'), ('user_management', 'User Management'), ('notice_management', 'Notices'), ('trip_management', 'Trip Management'), ('settings_management', 'System Settings')], max_length=50)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_filter', models.BooleanField(default=False)),
                ('show_in_menu', models.BooleanField(default=False)),
                ('data_scope', models.CharField(choices=[('national', 'National — all data'), ('state', 'State — assigned state(s) only'), ('manufacturer', "Manufacturer — own company's devices only"), ('district', 'District — assigned district(s) only'), ('dealer', 'Dealer — own handled devices only'), ('owner', 'Owner — own vehicles only'), ('self', 'Self — own records only'), ('none', 'None — no data access')], default='none', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='skytron_api.userroletype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbac_configs_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Permission Config',
                'verbose_name_plural': 'Role Permission Configs',
                'ordering': ['role', 'module'],
                'unique_together': {('role', 'module')},
            },
        ),
    ]
