# Generated by Django 4.1.13 on 2024-08-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0044_alter_captcha_key_alter_requestlog_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='1f912fee73dd4424a0dee68cd2d7a09d', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='box_tamper_alert',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='emergency_status',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='gps_status',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='ignition_status',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='main_power_status',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='packet_status',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='gpslocation',
            name='gps_validity',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='gpslocation',
            name='latitude_direction',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='gpslocation',
            name='longitude_direction',
            field=models.CharField(max_length=5),
        ),
    ]
