# Generated by Django 4.2.17 on 2026-06-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0045_seed_rbac_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authorisation_letter',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Authorisation Letter File Path'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_card',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID Card File Path'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_card_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Card Name'),
        ),
    ]
