# Generated by Django 4.1.13 on 2024-08-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0045_alter_captcha_key_alter_gpsdata_box_tamper_alert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.CharField(default='6b9c4b9819fe480aa6db6d8867c1298f', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='alert_id',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='cell_id',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='digital_input_status',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='digital_output_status',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='gsm_signal_strength',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='lac',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='latitude_dir',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='longitude_dir',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='mcc',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='mnc',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='nbr1_cell_id',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='nbr1_lac',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='nbr1_signal_strength',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='nbr2_cell_id',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='nbr2_lac',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='nbr2_signal_strength',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='nbr3_cell_id',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='nbr3_lac',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='nbr3_signal_strength',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='nbr4_cell_id',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='nbr4_lac',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='nbr4_signal_strength',
            field=models.CharField(max_length=6),
        ),
    ]
