# Generated by Django 4.2.17 on 2026-06-08 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0046_add_user_id_card_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_ref', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_phone', models.CharField(max_length=25)),
                ('applicant_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('title', models.CharField(max_length=500)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_review', 'In Review'), ('pending', 'Pending'), ('closed', 'Closed'), ('canceled', 'Canceled')], db_index=True, default='created', max_length=20)),
                ('source', models.CharField(choices=[('helpdesk_call', 'HelpDesk Call'), ('helpdesk_email', 'HelpDesk Email'), ('public_app', 'Public App')], default='public_app', max_length=20)),
                ('solution', models.TextField(blank=True, null=True)),
                ('final_report_file', models.CharField(blank=True, max_length=500, null=True)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Complaint Ticket',
                'verbose_name_plural': 'Complaint Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('stateadmin', 'State Admin'), ('devicemanufacture', 'Device Manufacture'), ('dealer', 'Dealer'), ('owner', 'Owner'), ('esimprovider', 'eSimProvider'), ('filment', 'Filment'), ('sosadmin', 'SOS Admin'), ('teamleader', 'Team Leader'), ('sosexecutive', 'SOS Executive'), ('schooladmin', 'School Admin'), ('parentuser', 'Parent User'), ('helpdesk', 'Help Desk')], max_length=20, verbose_name='Role'),
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='skytron_api.complaintticket')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('action_type', models.CharField(choices=[('created', 'Ticket Created'), ('status_change', 'Status Changed'), ('comment', 'Comment Added'), ('final_report', 'Final Report Submitted'), ('attachment', 'Attachment Added')], max_length=20)),
                ('old_value', models.CharField(blank=True, max_length=255, null=True)),
                ('new_value', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_activities', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='skytron_api.complaintticket')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='complaintticket',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_complaint_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
