# Generated by Django 4.2.17 on 2026-06-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0047_complaint_management'),
    ]

    operations = [
         
        migrations.AlterField(
            model_name='pointofinterests',
            name='mark_type',
            field=models.CharField(choices=[('Point', 'Point'), ('Road', 'Road'), ('Circle', 'Circle'), ('Polygon', 'Polygon')], max_length=40),
        ),
        migrations.AlterField(
            model_name='pointofinterests',
            name='use_type',
            field=models.CharField(choices=[('StateBoundary', 'StateBoundary'), ('DistrictBoundary', 'DistrictBoundary'), ('CityBoundary', 'CityBoundary'), ('VillageBoundary', 'VillageBoundary'), ('PermitRoute', 'PermitRoute'), ('Police', 'Police'), ('School', 'School'), ('Hospital', 'Hospital'), ('PoliceStation', 'PoliceStation'), ('BusStop', 'BusStop'), ('NoParking', 'NoParking'), ('Prohibited_Area', 'Prohibited_Area'), ('RailwayStation', 'RailwayStation'), ('Airport', 'Airport'), ('FuelStation', 'FuelStation'), ('TollGate', 'TollGate'), ('Other', 'Other'), ('Personal', 'Personal')], max_length=40),
        ),
    ]
