# Generated by Django 4.2.17 on 2026-06-10 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0048_requestlog_response_time_ms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('add', 'Add Whitelist'), ('remove', 'Remove Whitelist')], max_length=10)),
                ('requester_type', models.CharField(choices=[('manufacturer', 'Manufacturer'), ('dealer', 'Dealer')], max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('requester_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whitelist_requests', to='skytron_api.dealer')),
                ('device_stocks', models.ManyToManyField(related_name='whitelist_requests', to='skytron_api.devicestock')),
                ('esim_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelist_requests_received', to='skytron_api.esimprovider')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whitelist_requests', to='skytron_api.manufacturer')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelist_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhitelistRequestReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('denied', 'Denied')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('esim_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelist_reviews', to='skytron_api.esimprovider')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='skytron_api.whitelistrequest')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelist_reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhitelistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whitelist_type', models.CharField(choices=[('ip', 'IP Address'), ('url', 'URL'), ('phone', 'Phone Number'), ('apn', 'APN')], max_length=10)),
                ('value', models.CharField(max_length=500)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='skytron_api.whitelistrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whitelist_type', models.CharField(choices=[('ip', 'IP Address'), ('url', 'URL'), ('phone', 'Phone Number'), ('apn', 'APN')], max_length=10)),
                ('value', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('device_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_whitelists', to='skytron_api.devicestock')),
                ('esim_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_whitelists', to='skytron_api.esimprovider')),
                ('source_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_entries', to='skytron_api.whitelistrequest')),
            ],
            options={
                'ordering': ['-activated_at'],
            },
        ),
    ]
