# Generated by Django 4.2.17 on 2026-06-10 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0049_whitelist_request_management'),
    ]

    operations = [
        
        
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, help_text='Optional nickname for this favorite', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorited_by', to='skytron_api.devicetag')),
                ('bus_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorited_by', to='skytron_api.publicbusstop')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorited_by', to='skytron_api.publicbusroute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
                'db_table': 'favorites_favorite',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='favorites_f_user_id_645357_idx'), models.Index(fields=['user', '-created_at'], name='favorites_f_user_id_3c3f17_idx'), models.Index(fields=['bus'], name='favorites_f_bus_id_b8aebf_idx'), models.Index(fields=['route'], name='favorites_f_route_i_9fa930_idx'), models.Index(fields=['bus_stop'], name='favorites_f_bus_sto_a728a7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.CheckConstraint(check=models.Q(('bus__isnull', False), ('route__isnull', False), ('bus_stop__isnull', False), _connector='OR'), name='favorite_at_least_one_reference'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('bus__isnull', False)), fields=('user', 'bus'), name='unique_user_bus_favorite'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('route__isnull', False)), fields=('user', 'route'), name='unique_user_route_favorite'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('bus_stop__isnull', False)), fields=('user', 'bus_stop'), name='unique_user_busstop_favorite'),
        ),
    ]
