# Generated by Django 4.2.17 on 2026-06-11 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0050_requestlog_response_time_ms_favorite_and_more'),
    ]

    operations = [
        # ----------------------------------------------------------------
        # response_time_ms already exists in the database (it was added
        # manually before being recorded in a migration).
        # SeparateDatabaseAndState updates Django's migration state only —
        # no ALTER TABLE is executed — so this will never fail again.
        # ----------------------------------------------------------------
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='requestlog',
                    name='response_time_ms',
                    field=models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
            database_operations=[],  # column already in DB — skip
        ),

        # KYC fields on DeviceStock
        migrations.AddField(
            model_name='devicestock',
            name='kyc_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicestock',
            name='kyc_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='devicestock',
            name='kyc_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicestock',
            name='kyc_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_updates_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicestock',
            name='last_kyc_date',
            field=models.DateTimeField(blank=True, null=True),
        ),

        # New DeviceActivationLog model
        migrations.CreateModel(
            name='DeviceActivationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=55)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activation_log_entries', to=settings.AUTH_USER_MODEL)),
                ('device_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_logs', to='skytron_api.devicestock')),
                ('esim_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activation_logs', to='skytron_api.esimprovider')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
