# Generated by Django 4.2.17 on 2026-06-11 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0052_add_vehicle_category_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=10)),
                ('subrule_logic', models.CharField(choices=[('AND', 'AND — all subrules must match'), ('OR', 'OR  — any subrule must match')], default='AND', max_length=3)),
                ('time_from', models.TimeField(blank=True, help_text='Rule only evaluates after this time (IST)', null=True)),
                ('time_to', models.TimeField(blank=True, help_text='Rule only evaluates before this time (IST)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_custom_alert_rules', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, help_text='Leave blank for global scope (superadmin). State admins auto-set this.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_alert_rules', to='skytron_api.settings_state')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomAlertSubrule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Display order 1–4')),
                ('parameter', models.CharField(choices=[('speed', 'Speed'), ('altitude', 'Altitude'), ('satellites', 'Satellites'), ('pdop', 'PDOP'), ('hdop', 'HDOP'), ('heading', 'Heading'), ('odometer', 'Odometer'), ('main_input_voltage', 'Main Input Voltage'), ('internal_battery_voltage', 'Internal Battery Voltage'), ('frame_number', 'Frame Number'), ('packet_type', 'Packet Type'), ('alert_id', 'Alert ID'), ('packet_status', 'Packet Status'), ('gps_status', 'GPS Status'), ('ignition_status', 'Ignition Status'), ('main_power_status', 'Main Power Status'), ('emergency_status', 'Emergency Status'), ('box_tamper_alert', 'Box Tamper Alert'), ('network_operator', 'Network Operator'), ('gsm_signal_strength', 'GSM Signal Strength'), ('digital_input_status', 'Digital Input Status'), ('digital_output_status', 'Digital Output Status')], max_length=50)),
                ('operator', models.CharField(choices=[('==', 'Equal to (==)'), ('!=', 'Not equal to (!=)'), ('>', 'Greater than (>)'), ('>=', 'Greater than or equal to (>=)'), ('<', 'Less than (<)'), ('<=', 'Less than or equal to (<=)'), ('in_range', 'In range (start–end)'), ('contains', 'Contains (text)'), ('not_contains', 'Does not contain (text)')], max_length=15)),
                ('value', models.CharField(blank=True, help_text='Single comparison value', max_length=255)),
                ('value_start', models.CharField(blank=True, help_text='Range start (in_range only)', max_length=255)),
                ('value_end', models.CharField(blank=True, help_text='Range end (in_range only)', max_length=255)),
                ('time_from', models.TimeField(blank=True, null=True)),
                ('time_to', models.TimeField(blank=True, null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subrules', to='skytron_api.customalertrule')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CustomAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fired_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('details', models.TextField(blank=True, help_text='Human-readable summary of which subrules matched')),
                ('device_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_alert_logs', to='skytron_api.devicetag')),
                ('gps_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_alert_logs', to='skytron_api.gpsdata')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='skytron_api.customalertrule')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skytron_api.settings_state')),
            ],
            options={
                'ordering': ['-fired_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='customalertsubrule',
            constraint=models.UniqueConstraint(fields=('rule', 'order'), name='unique_subrule_order_per_rule'),
        ),
        migrations.AddIndex(
            model_name='customalertrule',
            index=models.Index(fields=['status'], name='skytron_api_status_a54879_idx'),
        ),
        migrations.AddIndex(
            model_name='customalertrule',
            index=models.Index(fields=['state', 'status'], name='skytron_api_state_i_1cbf73_idx'),
        ),
        migrations.AddIndex(
            model_name='customalertlog',
            index=models.Index(fields=['rule', 'fired_at'], name='skytron_api_rule_id_0af402_idx'),
        ),
        migrations.AddIndex(
            model_name='customalertlog',
            index=models.Index(fields=['device_tag', 'fired_at'], name='skytron_api_device__b776a1_idx'),
        ),
        migrations.AddIndex(
            model_name='customalertlog',
            index=models.Index(fields=['state', 'fired_at'], name='skytron_api_state_i_1b6cab_idx'),
        ),
    ]
