# Generated by Django 4.2.17 on 2026-06-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0053_customalertrule_customalertsubrule_customalertlog_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gpsdata',
            index=models.Index(fields=['device_tag', 'id'], name='gpsdata_tag_id_asc_idx'),
        ),
    ]
