# Generated by Django 4.2.17 on 2026-07-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0067_blekey_imei_active_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetag',
            name='trailer_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='devicetag',
            name='with_trailer',
            field=models.BooleanField(default=False),
        ),
    ]
