# Generated by Django 4.2.17 on 2026-07-17 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0068_device_tag_trailer_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationCommandDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=55)),
                ('activation_code', models.CharField(max_length=20)),
                ('command_sent', models.CharField(max_length=255)),
                ('send_status', models.CharField(choices=[('queued', 'Queued'), ('failed', 'Failed'), ('replied', 'Replied')], default='queued', max_length=10)),
                ('sent_at', models.DateTimeField()),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='activationcommandreply',
            name='activation_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='activationcommandreply',
            index=models.Index(fields=['activation_code'], name='skytron_api_activat_34297b_idx'),
        ),
        migrations.AddField(
            model_name='activationcommanddispatch',
            name='device_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_command_dispatches', to='skytron_api.devicetag'),
        ),
        migrations.AddField(
            model_name='activationcommanddispatch',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch', to='skytron_api.activationcommandreply'),
        ),
        migrations.AddField(
            model_name='activationcommanddispatch',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activation_commands_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activationcommanddispatch',
            index=models.Index(fields=['imei'], name='skytron_api_imei_bc1c31_idx'),
        ),
        migrations.AddIndex(
            model_name='activationcommanddispatch',
            index=models.Index(fields=['sent_at'], name='skytron_api_sent_at_913c78_idx'),
        ),
        migrations.AddIndex(
            model_name='activationcommanddispatch',
            index=models.Index(fields=['send_status'], name='skytron_api_send_st_8b9bf1_idx'),
        ),
    ]
