# Generated by Django 4.2.17 on 2026-07-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0069_activation_command_dispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='api_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
