# Generated by Django 4.2.17 on 2026-07-25 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0070_device_model_api_url_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStockUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='devicestock',
            name='esim_status',
            field=models.CharField(choices=[('NotAssigned', 'NotAssigned'), ('In_transit_to_dealer', 'In Transit to Dealer'), ('Available_for_fitting', 'Available for Fitting'), ('Fitted', 'Fitted'), ('ESIM_Active_Req_Sent', 'ESIM Active Request Sent'), ('ESIM_Active_Confirmed', 'ESIM Active Confirmed'), ('ESIM_Active_Rejected', 'ESIM_Active_Rejected'), ('IP_PORT_Configured', 'IP Port Configured'), ('SOS_GATEWAY_NO_Configured', 'SOS Gateway No Configured'), ('SMS_GATEWAY_NO_Configured', 'SMS Gateway No Configured'), ('Device_Defective', 'Device Defective'), ('Returned_to_manufacturer', 'Returned to Manufacturer'), ('Device_Untagged', 'Device Untagged'), ('Deleted', 'Deleted')], max_length=55),
        ),
        migrations.AlterField(
            model_name='devicestock',
            name='stock_status',
            field=models.CharField(choices=[('NotAssigned', 'NotAssigned'), ('In_transit_to_dealer', 'In Transit to Dealer'), ('Available_for_fitting', 'Available for Fitting'), ('Fitted', 'Fitted'), ('ESIM_Active_Req_Sent', 'ESIM Active Request Sent'), ('ESIM_Active_Confirmed', 'ESIM Active Confirmed'), ('ESIM_Active_Rejected', 'ESIM_Active_Rejected'), ('IP_PORT_Configured', 'IP Port Configured'), ('SOS_GATEWAY_NO_Configured', 'SOS Gateway No Configured'), ('SMS_GATEWAY_NO_Configured', 'SMS Gateway No Configured'), ('Device_Defective', 'Device Defective'), ('Returned_to_manufacturer', 'Returned to Manufacturer'), ('Device_Untagged', 'Device Untagged'), ('Deleted', 'Deleted')], max_length=55),
        ),
        migrations.AddField(
            model_name='devicestockuploadbatch',
            name='device_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_upload_batches', to='skytron_api.devicemodel'),
        ),
        migrations.AddField(
            model_name='devicestockuploadbatch',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_stock_upload_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicestock',
            name='upload_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_stocks', to='skytron_api.devicestockuploadbatch'),
        ),
    ]
