# Generated by Django 4.2.17 on 2026-07-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0071_devicestockuploadbatch_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicefirmwarelog',
            new_name='skytron_api_device__58552e_idx',
            old_name='dev_fw_log_tag_dt_idx',
        ),
        migrations.AlterField(
            model_name='alertslog',
            name='type',
            field=models.CharField(choices=[('Route', 'Route Deviation'), ('Geofence', 'Geofence'), ('Idling', 'Idling'), ('OfflineDevice', 'OfflineDevice'), ('Overtime', 'Overtime'), ('UnauthorizedStop', 'Unauthorized Stop'), ('UnauthorizedSkip', 'Unauthorized Skip'), ('NetworkLoss', 'Network Loss'), ('GPSLoss', 'GPS Loss'), ('Permit', 'Permit'), ('Permit_3day', 'Permit Expiring Soon'), ('Route_overspeed', 'Route Overspeed'), ('state_border_cross', 'State Border Cross'), ('district_border_cross', 'District Border Cross'), ('city_border_cross', 'City Border Cross'), ('Incident', 'Incident'), ('Em', 'Emergency SOS'), ('EmPublicApp', 'EmPublicApp'), ('EmRegisteredApp', 'EmRegisteredApp'), ('EmMonitorTripSOS', 'EmMonitorTripSOS'), ('EmMonitorTripInvalidPw', 'EmMonitorTripInvalidPw'), ('EmMonitorTripBLEDisconnect', 'EmMonitorTripBLEDisconnect'), ('EmMonitorTripDeviated', 'EmMonitorTripDeviated'), ('Eng', 'Engine Status'), ('OverSpeed', 'Over Speed'), ('LowIntBat', 'Low Internal Battery'), ('LowExtBat', 'Low External Battery'), ('ExtBatDiscnt', 'External Battery Disconnected'), ('BoxTemp', 'Box Temperature'), ('EmTemp', 'Emergency Temperature'), ('Tilt', 'Tilt'), ('HarshBreak', 'Harsh Braking'), ('HarshTurn', 'Harsh Turn'), ('HarshAcceleration', 'Harsh Acceleration'), ('UnauthorizedParking', 'Unauthorized Parking'), ('Prohibited_Area', 'Prohibited Area')], max_length=50),
        ),
        migrations.AlterField(
            model_name='devicefirmwarelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
