# Generated by Django 4.2.17 on 2026-07-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0072_rename_dev_fw_log_tag_dt_idx_skytron_api_device__58552e_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alertslog',
            index=models.Index(fields=['deviceTag', 'type', '-timestamp'], name='alertslog_tag_type_ts_idx'),
        ),
    ]
