# Generated by Django 4.2.17 on 2026-08-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0073_alertslog_tag_type_ts_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='emgpslocation',
            name='packet_format',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gpsdata',
            name='ain1_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsdata',
            name='ain2_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsdata',
            name='ota_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsdata',
            name='packet_format',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
