# Generated by Django 4.2.17 on 2026-08-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0074_emgpslocation_packet_format_gpsdata_ain1_voltage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esimprovider',
            name='m2m_api_last_tested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='esimprovider',
            name='m2m_api_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='esimprovider',
            name='m2m_api_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='esimprovider',
            name='m2m_api_verified',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='esimprovider',
            name='m2m_api_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='esimprovider',
            name='m2m_last_test_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='esimprovider',
            name='m2m_sample_iccid',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='esimprovider',
            name='m2m_technical_onboarding_status',
            field=models.CharField(choices=[('incorrect_api', 'Incorrect API'), ('invalid_format', 'API Data Format Invalid'), ('token_expired', 'Token Expired'), ('ok', 'Ok')], default='incorrect_api', max_length=20),
        ),
    ]
