# Generated by Django 4.2.17 on 2026-08-14 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0075_esimprovider_m2m_api_last_tested_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStockMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.PositiveSmallIntegerField(choices=[(2, 'Step 2 - eSIM Verification Pending'), (3, 'Step 3 - Dealer OTP Pending'), (4, 'Step 4 - GPS Packet Check Pending'), (5, 'Step 5 - Owner OTP Pending'), (6, 'Completed')], db_index=True, default=2)),
                ('step1_completed_at', models.DateTimeField()),
                ('step2_completed_at', models.DateTimeField(blank=True, null=True)),
                ('step3_completed_at', models.DateTimeField(blank=True, null=True)),
                ('step4_completed_at', models.DateTimeField(blank=True, null=True)),
                ('step5_completed_at', models.DateTimeField(blank=True, null=True)),
                ('imei', models.CharField(db_index=True, max_length=55)),
                ('iccid', models.CharField(db_index=True, max_length=55)),
                ('vahan_chassis_no', models.CharField(max_length=100)),
                ('vahan_device_activation_status', models.CharField(max_length=50)),
                ('vahan_device_serial_no', models.CharField(max_length=100)),
                ('vahan_engine_no', models.CharField(max_length=100)),
                ('vahan_fitment_centre_name', models.CharField(max_length=255)),
                ('vahan_gnss_constellation_code', models.CharField(max_length=100)),
                ('vahan_imei', models.CharField(max_length=55)),
                ('vahan_maker_name', models.CharField(max_length=255)),
                ('vahan_model_name', models.CharField(max_length=255)),
                ('vahan_owner_name', models.CharField(max_length=255)),
                ('vahan_tac_no', models.CharField(max_length=100)),
                ('vahan_tac_valid_upto', models.DateField()),
                ('vahan_veh_class', models.CharField(max_length=100)),
                ('vahan_raw_response', models.JSONField()),
                ('vahan_iccid', models.CharField(blank=True, default='', max_length=55)),
                ('vahan_reg_no', models.CharField(blank=True, default='', max_length=55)),
                ('vahan_date_of_registration', models.DateField(blank=True, null=True)),
                ('m2m_iccid', models.CharField(blank=True, max_length=55, null=True)),
                ('m2m_card_state', models.CharField(blank=True, max_length=50, null=True)),
                ('m2m_card_status', models.CharField(blank=True, max_length=50, null=True)),
                ('m2m_activation_date', models.DateField(blank=True, null=True)),
                ('m2m_expiry_date', models.DateField(blank=True, null=True)),
                ('m2m_primary_tsp', models.CharField(blank=True, max_length=100, null=True)),
                ('m2m_primary_msisdn', models.CharField(blank=True, max_length=55, null=True)),
                ('m2m_primary_status', models.CharField(blank=True, max_length=50, null=True)),
                ('m2m_fallback_tsp', models.CharField(blank=True, max_length=100, null=True)),
                ('m2m_fallback_msisdn', models.CharField(blank=True, max_length=55, null=True)),
                ('m2m_fallback_status', models.CharField(blank=True, max_length=50, null=True)),
                ('m2m_data_usage', models.CharField(blank=True, max_length=50, null=True)),
                ('m2m_data_usage_date', models.DateField(blank=True, null=True)),
                ('m2m_raw_response', models.JSONField(blank=True, null=True)),
                ('dealer_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('dealer_otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('dealer_otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('packet_results', models.JSONField(blank=True, null=True)),
                ('packets_all_received', models.BooleanField(blank=True, default=None, null=True)),
                ('packets_checked_at', models.DateTimeField(blank=True, null=True)),
                ('packet_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('packet_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('owner_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('owner_otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('owner_otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_stock_master_entries', to=settings.AUTH_USER_MODEL)),
                ('created_device_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_master_source', to='skytron_api.devicestock')),
                ('created_device_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_master_source', to='skytron_api.devicetag')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_master_entries', to='skytron_api.dealer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_stock_master_entries', to=settings.AUTH_USER_MODEL)),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_master_entries', to='skytron_api.devicemodel')),
                ('esim_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_master_entries', to='skytron_api.esimprovider')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_master_entries', to='skytron_api.manufacturer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_stock_master_entries', to=settings.AUTH_USER_MODEL)),
                ('vehicle_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_master_entries', to='skytron_api.vehicleowner')),
            ],
            options={
                'indexes': [models.Index(fields=['created_by', 'is_deleted'], name='skytron_api_created_d1f99c_idx'), models.Index(fields=['imei', 'is_deleted'], name='skytron_api_imei_102dc2_idx'), models.Index(fields=['iccid', 'is_deleted'], name='skytron_api_iccid_7a6854_idx'), models.Index(fields=['current_step', 'is_deleted'], name='skytron_api_current_21cf0f_idx'), models.Index(fields=['dealer', 'current_step'], name='skytron_api_dealer__97da42_idx')],
            },
        ),
    ]
