# Generated by Django 4.2.17 on 2026-08-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0076_devicestockmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestockmaster',
            name='dealer_otp_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devicestockmaster',
            name='owner_otp_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
