# Generated by Django 4.2.17 on 2026-08-17 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0077_devicestockmaster_dealer_otp_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestockmaster',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='stock_master_entries', to='skytron_api.settings_vehiclecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicestockmaster',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='stock_master_entries', to='skytron_api.settings_district'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicestockmaster',
            name='is_temp_reg_no',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='devicestockmaster',
            name='rc_file',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
