# Generated by Django 4.2.17 on 2026-08-19 06:33

from django.db import migrations, models


def set_sane_max_sessions_default(apps, schema_editor):
    """
    Existing LoginSettings rows were all left at the old default of 0
    (unlimited concurrent sessions) - nobody had explicitly configured this.
    Give them a real cap instead of silently staying unlimited forever.
    """
    LoginSettings = apps.get_model('skytron_api', 'LoginSettings')
    LoginSettings.objects.filter(max_simultaneous_sessions=0).update(max_simultaneous_sessions=3)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0078_devicestockmaster_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='otp_attempts',
            field=models.IntegerField(default=0, verbose_name='OTP Verification Attempts'),
        ),
        migrations.AlterField(
            model_name='loginsettings',
            name='max_simultaneous_sessions',
            field=models.IntegerField(default=3, help_text='Maximum number of simultaneous active sessions allowed. 0 = unlimited', verbose_name='Max Simultaneous Sessions'),
        ),
        migrations.RunPython(set_sane_max_sessions_default, noop),
    ]
