# Generated by Django 4.2.17 on 2026-08-19 06:48

from django.db import migrations, models


def lower_default_max_sessions(apps, schema_editor):
    """
    Migration 0079 just bumped every unconfigured (0) row to 3. Nobody has
    had a chance to customize that yet, so move those same still-default
    rows down to the new sane default of 2 rather than leaving them at 3.
    """
    LoginSettings = apps.get_model('skytron_api', 'LoginSettings')
    LoginSettings.objects.filter(max_simultaneous_sessions=3).update(max_simultaneous_sessions=2)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0079_session_otp_attempts_and_login_settings_cap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginsettings',
            name='max_simultaneous_sessions',
            field=models.IntegerField(default=2, help_text='Maximum number of simultaneous active sessions allowed. 0 = unlimited', verbose_name='Max Simultaneous Sessions'),
        ),
        migrations.RunPython(lower_default_max_sessions, noop),
    ]
