# Generated by Django 4.2.17 on 2026-08-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0080_login_settings_max_sessions_default_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='VahanDummyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=55, unique=True)),
                ('reg_no', models.CharField(blank=True, default='', max_length=55)),
                ('date_of_registration', models.DateField(blank=True, null=True)),
                ('chassis_no', models.CharField(max_length=100)),
                ('engine_no', models.CharField(max_length=100)),
                ('device_serial_no', models.CharField(max_length=100)),
                ('veh_class', models.CharField(max_length=100)),
                ('maker_name', models.CharField(default='Pricol SGPCA SLD', max_length=255)),
                ('model_name', models.CharField(default='ASMTEST', max_length=255)),
                ('owner_name', models.CharField(default='TEST OWNER', max_length=255)),
                ('fitment_centre_name', models.CharField(default='Skytron Test Fitment Centre', max_length=255)),
                ('gnss_constellation_code', models.CharField(default='5,2,6,1,3', max_length=100)),
                ('device_activation_status', models.CharField(default='PENDING', max_length=50)),
                ('tac_no', models.CharField(default='SKYTRON09', max_length=100)),
                ('tac_valid_upto', models.DateField(blank=True, null=True)),
                ('iccid', models.CharField(blank=True, default='', max_length=55)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vahan Dummy Data',
                'verbose_name_plural': 'Vahan Dummy Data',
                'ordering': ['imei'],
            },
        ),
    ]
