# Generated by Django 4.2.17 on 2026-08-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0081_vahandummydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='whitelisted_ip',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='esimprovider',
            name='device_ip_range',
            field=models.TextField(blank=True, default=''),
        ),
    ]
