# Generated by Django 4.2.17 on 2026-08-22 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0082_devicemodel_whitelisted_ip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalOnboardingTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.PositiveSmallIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source_table', models.CharField(choices=[('gps', 'GPS Raw Log (GPSDataLog)'), ('gpsem', 'Emergency Raw Log (GPSemDataLog)'), ('ota_command', 'OTA Command History'), ('activation_command', 'Activation Command'), ('manual', 'Manual / Observed')], default='manual', max_length=20)),
                ('regex_pattern', models.CharField(blank=True, max_length=500, null=True)),
                ('min_match_count', models.PositiveIntegerField(default=1)),
                ('max_interval_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('scan_window_seconds', models.PositiveIntegerField(default=300)),
                ('is_optional', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['serial_no'],
            },
        ),
        migrations.AddField(
            model_name='devicemodeltechnicalonboardingdemodevice',
            name='receipt_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devicemodeltechnicalonboardingdemodevice',
            name='receipt_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicemodeltechnicalonboardingdemodevice',
            name='receipt_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicemodeltechnicalonboardingrequest',
            name='courier_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='devicemodeltechnicalonboardingrequest',
            name='courier_shipped_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicemodeltechnicalonboardingrequest',
            name='courier_tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='devicemodeltechnicalonboardingrequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('stock_received', 'Stock Received'), ('ongoing_evaluation', 'Ongoing Evaluation'), ('testing_complete', 'Testing Complete'), ('technically_compatible', 'Technically Compatible'), ('technically_not_compatible', 'Technically Not Compatible'), ('StateAdminApproved', 'State Admin Approved'), ('StateAdminRejected', 'State Admin Rejected')], db_index=True, default='submitted', max_length=30),
        ),
        migrations.CreateModel(
            name='TechnicalOnboardingTestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('incomplete', 'Incomplete')], db_index=True, default='not_started', max_length=15)),
                ('attempt_number', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('test_log_snapshot', models.JSONField(blank=True, null=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('manual_result', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=4, null=True)),
                ('manual_notes', models.TextField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('demo_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_executions', to='skytron_api.devicemodeltechnicalonboardingdemodevice')),
                ('onboarding_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_executions', to='skytron_api.devicemodeltechnicalonboardingrequest')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='skytron_api.technicalonboardingtestcase')),
            ],
            options={
                'indexes': [models.Index(fields=['onboarding_request', 'test_case'], name='skytron_api_onboard_1d759e_idx'), models.Index(fields=['onboarding_request', 'status'], name='skytron_api_onboard_4d8dcf_idx')],
                'unique_together': {('onboarding_request', 'demo_device', 'test_case')},
            },
        ),
    ]
