# Generated by Django 4.2.17 on 2026-08-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0082_devicemodel_whitelisted_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestockmaster',
            name='device_sell_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='devicestockmaster',
            name='no_of_emg_buttons',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicetag',
            name='no_of_emg_buttons',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
