# Generated by Django 4.2.17 on 2026-08-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0083_devicestockmaster_device_sell_amount_and_more'),
        ('skytron_api', '0084_seed_technical_onboarding_test_cases'),
    ]

    operations = [
    ]
