# Generated by Django 4.2.17 on 2026-08-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0085_merge_20260825_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='device_ip_range',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='threshold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='whitelisted_phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
