# Generated by Django 4.2.17 on 2026-08-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0085_merge_20260825_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalonboardingtestcase',
            name='requires_manual_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
