# Generated by Django 4.2.17 on 2026-08-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0086_add_test_case_manual_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalonboardingtestcase',
            name='source_table',
            field=models.CharField(choices=[('gps', 'GPS Raw Log (GPSDataLog)'), ('gpsem', 'Emergency Raw Log (GPSemDataLog)'), ('ota_command', 'OTA Command History'), ('activation_command', 'Activation Command'), ('firmware_diff', 'Firmware Version Change (GPSDataLog)'), ('manual', 'Manual / Observed')], default='manual', max_length=20),
        ),
    ]
