# Generated by Django 4.2.17 on 2026-08-28 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0086_devicemodel_device_ip_range_devicemodel_threshold_and_more'),
        ('skytron_api', '0087_add_firmware_diff_source_choice'),
    ]

    operations = [
    ]
