# Generated by Django 4.2.17 on 2026-08-31 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0088_merge_20260828_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='eSimProviderIPRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_range', models.CharField(max_length=100)),
                ('certificate_file', models.CharField(blank=True, max_length=255, null=True)),
                ('isp_name', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_ranges', to='skytron_api.esimprovider')),
            ],
        ),
    ]
