# Generated by Django 4.2.17 on 2026-09-01 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0089_esimprovideriprange'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetag',
            name='esim_provider',
            field=models.ForeignKey(blank=True, help_text='The M2M provider chosen for this device during tagging.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_tags', to='skytron_api.esimprovider'),
        ),
    ]
