# Generated by Django 4.2.17 on 2026-09-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0090_devicetag_esim_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='emgpslocation',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsdata',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsdatalog',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsemdatalog',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
    ]
