# Generated by Django 4.2.17 on 2026-09-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0090_fix_onboarding_check_thresholds'),
        ('skytron_api', '0091_emgpslocation_source_ip_gpsdata_source_ip_and_more'),
    ]

    operations = [
    ]
