# Generated by Django 4.2.17 on 2026-09-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0092_merge_20260901_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='provider_combinations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
