# Generated by Django 4.2.17 on 2026-09-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0093_devicemodel_provider_combinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestockmaster',
            name='provider_combination',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
