# Generated by Django 4.2.17 on 2026-09-15 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0094_devicestockmaster_provider_combination'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRenewalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_role', models.CharField(choices=[('dealer', 'Dealer'), ('devicemanufacture', 'Manufacturer')], max_length=20)),
                ('requested_duration_years', models.PositiveSmallIntegerField(choices=[(1, '1 Year'), (2, '2 Years')])),
                ('old_esim_validity', models.DateTimeField(blank=True, null=True)),
                ('new_esim_validity', models.DateTimeField(blank=True, null=True)),
                ('m2m_raw_response', models.JSONField(blank=True, null=True)),
                ('m2m_checked_at', models.DateTimeField(blank=True, null=True)),
                ('packet_results', models.JSONField(blank=True, null=True)),
                ('packets_all_received', models.BooleanField(blank=True, default=None, null=True)),
                ('packets_checked_at', models.DateTimeField(blank=True, null=True)),
                ('pvt_precheck_details', models.JSONField(blank=True, null=True)),
                ('vahan_push_status', models.CharField(blank=True, choices=[('not_attempted', 'Not Attempted'), ('success', 'Success'), ('failed', 'Failed')], max_length=20, null=True)),
                ('vahan_push_response', models.JSONField(blank=True, null=True)),
                ('vahan_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate_generated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_requests', to='skytron_api.dealer')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_requests', to='skytron_api.devicestock')),
                ('device_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_requests', to='skytron_api.devicetag')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_requests', to='skytron_api.manufacturer')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'status'], name='skytron_api_device__fc0551_idx'), models.Index(fields=['requested_by', 'created_at'], name='skytron_api_request_874bf9_idx'), models.Index(fields=['status', 'created_at'], name='skytron_api_status_0716b8_idx')],
            },
        ),
    ]
