# Generated by Django 4.2.17 on 2026-09-15 09:07
"""
Registers a new RBAC module (device_renewal_management) on
RolePermissionConfig.module and grants superadmin (national scope),
devicemanufacture (manufacturer scope) and dealer (dealer scope) view+create
access to it, matching how ota_command_management etc. were rolled out.
"""

from django.db import migrations, models


def seed_renewal_permissions(apps, schema_editor):
    UserRoleType = apps.get_model('skytron_api', 'UserRoleType')
    RolePermissionConfig = apps.get_model('skytron_api', 'RolePermissionConfig')

    role_scopes = {
        'superadmin': 'national',
        'devicemanufacture': 'manufacturer',
        'dealer': 'dealer',
    }

    for role_code, data_scope in role_scopes.items():
        role = UserRoleType.objects.filter(code=role_code).first()
        if role is None:
            continue
        RolePermissionConfig.objects.get_or_create(
            role=role,
            module='device_renewal_management',
            defaults={
                'can_view': True,
                'can_create': True,
                'can_update': False,
                'can_delete': False,
                'can_filter': True,
                'show_in_menu': True,
                'data_scope': data_scope,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0095_devicerenewalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermissionconfig',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('gps_tracking', 'GPS Live Tracking'), ('gps_history', 'GPS History'), ('gps_clustering', 'GPS Cluster / Grid'), ('device_management', 'Device Model Management'), ('device_stock', 'Device Stock & Inventory'), ('vehicle_tagging', 'Vehicle Tagging'), ('driver_management', 'Driver Management'), ('owner_management', 'Vehicle Owner Management'), ('manufacturer_management', 'Manufacturer Management'), ('dealer_management', 'Dealer Management'), ('stateadmin_management', 'State Admin Management'), ('esim_management', 'eSIM Provider Management'), ('emergency_management', 'Emergency (SOS) Management'), ('emergency_teams', 'Emergency Teams'), ('poi_management', 'Points of Interest'), ('route_management', 'Route Management'), ('alerts', 'Alerts & Notifications'), ('reports', 'Reports'), ('user_management', 'User Management'), ('notice_management', 'Notices'), ('trip_management', 'Trip Management'), ('settings_management', 'System Settings'), ('complaint', 'Complaint Management'), ('dashboard_north', 'North Dashboard'), ('dashboard_central', 'Central Dashboard'), ('sbs_dashboard', 'School Bus System — Dashboard'), ('sbs_bus_tagging', 'School Bus System — Bus Tagging'), ('sbs_route_mgmt', 'School Bus System — Route Management'), ('sbs_bus_assignment', 'School Bus System — Bus Assignment'), ('sbs_profile_mgmt', 'School Bus System — Profile Management'), ('sbs_school_reports', 'School Bus System — School Reports'), ('sbs_create_school', 'School Bus System — Create School'), ('sbs_approve_school', 'School Bus System — Approve School'), ('sbs_bus_tracking', 'School Bus System — School Bus Tracking'), ('sbs_create_trip', 'School Bus System — Create Trip'), ('sbs_parent_tracking', 'School Bus System — Parent Tracking'), ('ta_create_agency', 'Test Agency — Create Agency Details'), ('ta_agency_list', 'Test Agency — Agency Details List'), ('ta_create_user', 'Test Agency — Create Agency User'), ('ta_user_list', 'Test Agency — Agency User List'), ('ta_view_models', 'Test Agency — View Assigned Models'), ('cn_state_admin', 'Create New — State Admin'), ('cn_m2m_provider', 'Create New — M2M Service Provider'), ('cn_manufacturer', 'Create New — Manufacturer'), ('cn_sos_admin', 'Create New — SOS Admin'), ('cn_system_admin', 'Create New — System Admin'), ('cn_dto', 'Create New — DTO'), ('cn_dealer', 'Create New — Dealer Account'), ('cn_sos_user', 'Create New — SOS User'), ('cn_vehicle_owner', 'Create New — Vehicle Owner'), ('m2m_registration', 'M2M Registration Requests'), ('m2m_pending', 'M2M — Pending Activation Requests'), ('m2m_rejected', 'M2M — Rejected Requests'), ('m2m_accepted', 'M2M — Accepted Requests'), ('mfr_vlt_requests', 'Vehicle Manufacturer Requests'), ('mfr_ais140_requests', 'AIS-140 Manufacturer Requests'), ('tech_onboarding', 'Technical Onboarding Requests'), ('tech_onboarding_final', 'Technical Onboarding — Final Approval'), ('mfr_onboarding_new', 'Manufacturer Onboarding — New Request'), ('mfr_onboarding_list', 'Manufacturer Onboarding — My Requests'), ('route_fixing', 'Route Fixing'), ('live_tracking', 'Live Tracking'), ('history_playback', 'History Playback'), ('trip_viewer', 'Trip Viewer'), ('trip_monitor', 'Trip Monitor'), ('vltd_pending_model', 'VLTD — Pending Model Approval'), ('vltd_pending_cop', 'VLTD — Pending COP'), ('vltd_approved_models', 'VLTD — Approved Models'), ('vltd_approved_cops', 'VLTD — Approved COPs'), ('wkyc_requests', 'Whitelist & KYC — Whitelist Requests'), ('wkyc_device_dashboard', 'Whitelist & KYC — Device Dashboard'), ('poi_viewer', 'POI Viewer'), ('report_sos', 'Report — SOS'), ('report_notices', 'Report — Notices'), ('report_users', 'Report — Users'), ('report_state_admin', 'Report — State Admin'), ('report_manufacturer', 'Report — Manufacturer'), ('report_sos_admin', 'Report — SOS Admin'), ('report_m2m_provider', 'Report — M2M Provider'), ('report_dealers', 'Report — Dealers'), ('report_vehicle_owner', 'Report — Vehicle Owner'), ('report_dto', 'Report — DTO User List'), ('report_gps_log', 'Report — GPS Data Log'), ('report_activation_log', 'Report — Activation Log'), ('report_emergency_data', 'Report — Emergency Data Logs'), ('report_health_packet', 'Report — Health Packet Log'), ('report_event_data', 'Report — Event Data Log'), ('report_activated_device', 'Report — Activated Device'), ('report_alert', 'Report — Alert'), ('report_poi', 'Report — POI'), ('report_incident', 'Report — Incident'), ('report_device_health', 'Report — Device Health'), ('report_user_stats', 'Report — User Statistics'), ('report_violation', 'Report — Violation'), ('report_sos_users', 'Report — SOS Users'), ('report_sos_call_list', 'Report — SOS Call List'), ('report_stock', 'Report — Stock'), ('report_fitment', 'Report — Fitment'), ('report_device', 'Report — Device'), ('settings_notice', 'Settings — Notice'), ('settings_send_command', 'Settings — Send Command'), ('settings_vehicle_type', 'Settings — Vehicle Type'), ('settings_vehicle_category', 'Settings — Vehicle Category Code'), ('settings_alert_notif', 'Settings — Alert Notification Delivery Mode'), ('settings_state_district', 'Settings — State & District'), ('settings_ota_firmware', 'Settings — OTA & Firmware'), ('settings_archive_restore', 'Settings — Archive & Restore'), ('settings_ip', 'Settings — IP Settings'), ('settings_login', 'Settings — Login Settings'), ('settings_permit_cond', 'Settings — Permit Conditions'), ('settings_custom_alerts', 'Settings — Custom Alerts'), ('pis_bus_stops', 'PIS — Bus Stops'), ('pis_bus_routes', 'PIS — Bus Routes'), ('pis_bus_schedules', 'PIS — Bus Schedules'), ('sta_trip_analysis', 'Analytics — Trip Analysis'), ('sta_driving_patterns', 'Analytics — Driving Pattern Alerts'), ('sta_vehicle_alerts', 'Analytics — Vehicle Alerts Count'), ('sta_pis_summary', 'Analytics — PIS Summary'), ('sta_operational', 'Analytics — Operational Analytics'), ('sta_comparative', 'Analytics — Comparative Analysis'), ('sta_resource_perf', 'Analytics — Resource Performance'), ('cum_custom_roles', 'Custom User — Role Management'), ('cum_feature_perms', 'Custom User — Feature Permissions'), ('cum_user_mgmt', 'Custom User — User Management'), ('ct_my_dashboard', 'Complaints — My Ticket Dashboard'), ('ct_create', 'Complaints — Create Ticket'), ('ct_all_tickets', 'Complaints — All Tickets'), ('ct_escalated', 'Complaints — Escalated Tickets'), ('dm_create_model', 'Device — Create Model'), ('dm_tac_cop', 'Device — TAC/COP Extension'), ('ds_individual', 'Stock — Individual'), ('ds_bulk', 'Stock — Bulk'), ('ds_assign', 'Stock — Assign'), ('dealer_m2m_status', 'Dealer — Check M2M Status'), ('dealer_request_m2m', 'Dealer — Request M2M Activation'), ('dealer_tag_device', 'Dealer — Tag Device to Vehicle'), ('dealer_untagged', 'Dealer — UnTagged Devices'), ('dealer_download_cert', 'Dealer — Download Certificate'), ('em_team_create', 'EM Team — Create'), ('em_team_list', 'EM Team — List'), ('sos_call_list', 'SOS Call List'), ('ota_command_definition', 'OTA — Command Definitions'), ('ota_command_history', 'OTA — Command History & Send Command'), ('ota_value_suggestion', 'OTA — Value Suggestions'), ('device_renewal_management', 'Device eSIM Renewal Management')], max_length=50),
        ),
        migrations.RunPython(seed_renewal_permissions, migrations.RunPython.noop),
    ]
