# Generated by Django 4.2.17 on 2026-09-21 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0096_device_renewal_management_rbac'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodeltechnicalonboardingdemodevice',
            name='receipt_reject_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='devicemodeltechnicalonboardingdemodevice',
            name='receipt_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devicemodeltechnicalonboardingdemodevice',
            name='receipt_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicemodeltechnicalonboardingdemodevice',
            name='receipt_rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devicemodeltechnicalonboardingrequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('stock_received', 'Stock Received'), ('stock_rejected', 'Stock Rejected'), ('ongoing_evaluation', 'Ongoing Evaluation'), ('testing_complete', 'Testing Complete'), ('technically_compatible', 'Technically Compatible'), ('technically_not_compatible', 'Technically Not Compatible'), ('StateAdminApproved', 'State Admin Approved'), ('StateAdminRejected', 'State Admin Rejected')], db_index=True, default='submitted', max_length=30),
        ),
    ]
