# Generated by Django 4.2.17 on 2026-09-21 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0097_technical_onboarding_receipt_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='reject_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='status',
            field=models.CharField(choices=[('Manufacturer_OTP_Sent', 'Manufacturer OTP Sent'), ('Manufacturer_OTP_Verified', 'Manufacturer OTP Verified'), ('StateAdminOTPSend', 'State Admin OTP Sent'), ('StateAdminApproved', 'State Admin Approved'), ('StateAdminRejected', 'State Admin Rejected')], db_index=True, max_length=255),
        ),
    ]
