# Generated by Django 4.2.17 on 2026-09-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0099_onboarding_catalog_ignition_split_pvt_drop'),
    ]

    operations = [
        migrations.AddField(
            model_name='em_admin',
            name='file_authLetter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
