# Generated by Django 4.2.17 on 2026-09-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0100_em_admin_file_authletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='esimprovider',
            name='file_selfCertifiedCompanyPANCard',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='file_selfCertifiedCompanyPANCard',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
