# Generated by Django 4.2.17 on 2026-10-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skytron_api', '0106_datalog_imei_network_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BleSosAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ble_mac', models.CharField(max_length=17)),
                ('ble_device_name', models.CharField(blank=True, default='', max_length=100)),
                ('registration_no', models.CharField(max_length=20)),
                ('phone_device_id', models.CharField(max_length=128)),
                ('user_mobile', models.CharField(blank=True, default='', max_length=15)),
                ('sos_type', models.CharField(choices=[('BLE_Public', 'BLE Public'), ('BLE_Login', 'BLE Login'), ('BLE_TM_PW_Fail', 'BLE Trip Monitor Password Fail'), ('BLE_TM_Route', 'BLE Trip Monitor Route Violation')], max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('phone_battery', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('signal_strength_dbm', models.SmallIntegerField(blank=True, null=True)),
                ('cell_ids', models.JSONField(blank=True, default=list)),
                ('event_time', models.DateTimeField(blank=True, null=True)),
                ('app_version', models.CharField(blank=True, default='', max_length=30)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ble_sos_app_log',
                'indexes': [models.Index(fields=['-received_at'], name='blesos_received_idx'), models.Index(fields=['ble_mac', '-received_at'], name='blesos_mac_idx'), models.Index(fields=['registration_no', '-received_at'], name='blesos_regno_idx'), models.Index(fields=['phone_device_id', '-received_at'], name='blesos_phone_idx')],
            },
        ),
    ]
