listener 8883
protocol mqtt

cafile   /etc/mosquitto/certs/ca.crt
certfile /etc/mosquitto/certs/server.crt
keyfile  /etc/mosquitto/certs/server.key
tls_version tlsv1.2

require_certificate false
allow_anonymous false
log_type all
