"""
Django settings for Skytronsystem project.

Generated by 'django-admin startproject' using Django 4.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# mail_id = os.environ.get("MAIL_ID", "testskytrack@gmail.com")
# mail_pw = os.environ.get("MAIL_PW", " ")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', ' ')

# JWT RSA Keys Configuration (RS256 Algorithm)
# Paths to RSA private/public keys for JWT token signing
JWT_PRIVATE_KEY_PATH = os.path.join(BASE_DIR, 'keys', 'jwt_private_key.pem')
JWT_PUBLIC_KEY_PATH = os.path.join(BASE_DIR, 'keys', 'jwt_public_key.pem')

# MQTT Broker Configuration
# Set to a non-empty secret to enable throttle bypass via X-Load-Test-Token header.
# Used exclusively for JMeter / load-test runs. Leave blank (or unset) in production.
LOAD_TEST_SECRET = os.environ.get('LOAD_TEST_SECRET', '')

# Set DISABLE_THROTTLE=true to turn off ALL throttling (use only during load tests).
DISABLE_THROTTLE = os.environ.get('DISABLE_THROTTLE', 'false').lower() == 'true'

MQTT_HOST = os.environ.get('MQTT_HOST', '127.0.0.1')
MQTT_PORT = os.environ.get('MQTT_PORT', '8883')
MQTT_ADMIN_USER = os.environ.get('MQTT_ADMIN_USER', '')
MQTT_ADMIN_PASS = os.environ.get('MQTT_ADMIN_PASS', '')
MQTT_CA_FILE = os.environ.get('MQTT_CA_FILE', '/etc/mosquitto/certs/ca.crt')
# If True, any IMEI can connect via MQTT without password verification (dev/test mode)
ALLOW_ALL_DEV_MQTT = os.environ.get('ALLOWALLDEVMQTT', 'false').lower() == 'true'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',')
# ALLOWED_HOSTS = ['api.skytron.in', 'skytron.in','dev.skytron.in','api-dev.skytron.in', 'skytrack.tech']
# ['http://localhost:3000/','40.81.241.29','20.210.207.21','api.skytron.in','skytron.in','localhost','172.17.0.1','skytron.in','216.10.244.243','skytrack.tech','https://www.skytrack.tech','admiring-solomon.216-10-244-243.plesk.page']


# Secure cookies
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True

# Enforce HTTPS
"""SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_REFERRER_POLICY = 'strict-origin'
"""

DATA_UPLOAD_MAX_NUMBER_FIELD = 71193766
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get('DATA_UPLOAD_MAX_MEMORY_SIZE', str(30 * 1024 * 1024)))
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get('FILE_UPLOAD_MAX_MEMORY_SIZE', str(2 * 1024 * 1024)))
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'bootstrap4',
    'csp',
    'bootstrap_datepicker_plus',
    'drf_spectacular',
    'corsheaders',
    'skytron_api',
    "django_extensions",
    'rest_framework.authtoken',
]

FORM_RENDERER = 'django.forms.renderers.DjangoTemplates'
MIDDLEWARE = [

    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
    'skytron_api.middleware.RequestLoggerMiddleware'
]

# Content Security Policy settings
"""
CSP_DEFAULT_SRC = ("'self'",)  # Default source for all content types
CSP_SCRIPT_SRC = ("'self'", )  # For JavaScript
CSP_STYLE_SRC = ("'self'",)  # For CSS
CSP_IMG_SRC = ("'self'",)  # For images
CSP_FONT_SRC = ("'self'",)  # For fonts
CSP_CONNECT_SRC = ("'self'", )  # For AJAX, WebSockets
CSP_OBJECT_SRC = ("'none'",)  # Disallow plugins like Flash
CSP_FRAME_SRC = ("'self'",)  # Allowed iframes
CSP_MEDIA_SRC = ("'self'",)  # For media like audio and video

# Optionally report violations
CSP_REPORT_ONLY = False  # Set to True to test the policy without enforcing
CSP_REPORT_URI = 'https://'
"""


# Security settings
# Prevents the browser from guessing the content type
SECURE_CONTENT_TYPE_NOSNIFF = True
# Enables XSS protection in browsers that support it
SECURE_BROWSER_XSS_FILTER = True

"""
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'skytron_api.middleware.RequestLoggerMiddleware'      
"""

ROOT_URLCONF = 'Skytronsystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Skytronsystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Print database environment variables for debugging (disabled by default).
# Enable with DJANGO_PRINT_DB_ENV=1
if os.environ.get('DJANGO_PRINT_DB_ENV') == '1':
    def _mask_env(name: str) -> str:
        val = os.environ.get(name)
        if not val:
            return 'NOT SET'
        if name in {'DB_PASSWORD'}:
            return 'SET'
        return val

    print("=== DATABASE ENVIRONMENT VARIABLES ===")
    print(f"DB_NAME: {_mask_env('DB_NAME')}")
    print(f"DB_USER: {_mask_env('DB_USER')}")
    print(f"DB_PASSWORD: {_mask_env('DB_PASSWORD')}")
    print(f"DB_HOST: {_mask_env('DB_HOST')}")
    print(f"DB_PORT: {_mask_env('DB_PORT')}")
    print("========================================")

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'skytrondb_main'),
        'USER': os.environ.get('DB_USER', 'dbadmin'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'lask1028zmnx'),
        'HOST': os.environ.get('DB_HOST', ''),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_USER_MODEL = 'skytron_api.User'


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
]
CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
    "x-csrftoken",
]
CORS_ALLOWED_ORIGINS = ["https://www.skytrack.tech",
                        "http://localhost:3000",
                        "https://localhost:3000",
                        "https://skytrack.tech:3000",
                        "https://gromed.in",
                        "https://api.gromed.in",
                        "https://skytrack.tech:2000",
                        "https://skytrack.tech",
                        'https://skytron.in',
                        'https://api.skytron.in',
                        'https://skytron.in',
                        'https://dev-api.skytron.in', 'http://localhost:2031',
                        'http://dev-api.skytron.in',
                        'https://dev.skytron.in',
                        'http://dev.skytron.in',
                        'https://dev.skytron.in','http://10.192.136.184:2000','http://10.192.136.179:2000','http://10.192.136.175:2000','http://10.192.136.164:2000',
                        # Add your frontend domain(s) here
                        "https://dev.skytrack.tech",
                        "https://integration.skytron.in",
                        "https://test.skytron.in",
                        # "https://yourfrontenddomain.com",
                        # to allow all origins
                        ]
# VAPT: Do NOT allow all origins — use the explicit CORS_ALLOWED_ORIGINS list above
CORS_ALLOW_ALL_ORIGINS = False
# Cache preflight responses for 24 h so browsers don't re-issue OPTIONS frequently
CORS_PREFLIGHT_MAX_AGE = 86400
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# STATIC_URL = 'static/'


STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / '../staticfiles'

# WhiteNoise settings to enable static file compression and caching
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',  # For unauthenticated users
        'rest_framework.throttling.UserRateThrottle',  # For authenticated users
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10/minute',   # Limit anonymous users to 10 requests per minute (general APIs)
        'user': '1000/hour',    # Limit authenticated users to 1000 requests per hour (general APIs)
        'auth': '10/minute',     # Limit authentication endpoints to 10 requests per minute
        'login': '10/minute',    # Limit login endpoints to 10 requests per minute
        'otp': '10/minute',      # Limit OTP endpoints to 10 requests per minute
        'password_reset': '3/minute',  # Limit password reset to 3 requests per minute
        'alert_stats': '30/minute',    # Alert-statistics dashboard/summary
        'device_command': '20/minute', # Sending raw commands down to a live device
        'server_health': '10/minute',  # Internal server-health dashboard (superadmin only)
        'device_data_health': '20/minute',  # Device protocol-format validator lookups
    },

    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'skytron_api.jwt_authentication.HybridAuthentication',   
        'rest_framework.authentication.TokenAuthentication', 
    ],

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        # Module-level OR-gate: if the URL is in rbac_api_map, the user must
        # have 'view' on at least one of its mapped modules.  URLs not in the
        # map are allowed through (backward-compatible for un-mapped endpoints).
        'skytron_api.rbac.ModuleAccessPermission',
    ],

}


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
         "LOCATION": "redis://skytron-redis:6379/1",  # Redis DB index 1
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.titan.email'  # Use your email provider's SMTP server
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'noreply@skytron.in')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')


# OTP configuration
OTP_EXPIRY_MINUTES = 5
OTP_MAX_ATTEMPTS = 3

# Only expose OTP in development
SHOW_OTP_IN_RESPONSE = DEBUG

# (for testing phase only)
ALLOW_DEFAULT_TEST_OTP = True
DEFAULT_TEST_OTP = "685472"


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]
LOGIN_URL = 'admin:login'
LOGIN_REDIRECT_URL = 'admin:index'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs/errors.log',
        },
        'console': {
            'level': 'ERROR',
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stdout',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}
